In [2]:
%pip install transformers

Collecting transformers
  Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
Collecting filelock (from transformers)
  Downloading filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
Collecting huggingface-hub<1.0,>=0.26.0 (from transformers)
  Downloading huggingface_hub-0.29.3-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from transformers) (2.2.2)
Requirement already satisfied: packaging>=20.0 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from transformers) (24.2)
Collecting pyyaml>=5.1 (from transformers)
  Downloading PyYAML-6.0.2-cp310-cp310-win_amd64.whl.metadata (2.1 kB)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2024.11.6-cp310-cp310-win_amd64.whl.metadata (41 kB)
Requirement already satisfied: requests in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from transformers) (2.32.3)
Collecting tokenizers<0.22,>=0.21 (from transformers)
  Downloading tokenizers-0.21.0-cp39-abi3-win_amd64.whl.metadata (6.9 kB)
Collecting safetensors>=0.4.1 (from transformers)
  Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: tqdm>=4.27 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from transformers) (4.67.1)
Collecting fsspec>=2023.5.0 (from huggingface-hub<1.0,>=0.26.0->transformers)
  Downloading fsspec-2025.3.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from huggingface-hub<1.0,>=0.26.0->transformers) (4.12.2)
Requirement already satisfied: colorama in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from requests->transformers) (2025.1.31)
Downloading transformers-4.49.0-py3-none-any.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ------------------ --------------------- 4.7/10.0 MB 25.9 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.0 MB 24.9 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 23.9 MB/s eta 0:00:00
Downloading huggingface_hub-0.29.3-py3-none-any.whl (468 kB)
Downloading PyYAML-6.0.2-cp310-cp310-win_amd64.whl (161 kB)
Downloading regex-2024.11.6-cp310-cp310-win_amd64.whl (274 kB)
Downloading safetensors-0.5.3-cp38-abi3-win_amd64.whl (308 kB)
Downloading tokenizers-0.21.0-cp39-abi3-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ---------------------------------------- 2.4/2.4 MB 19.5 MB/s eta 0:00:00
Downloading filelock-3.17.0-py3-none-any.whl (16 kB)
Downloading fsspec-2025.3.0-py3-none-any.whl (193 kB)
Installing collected packages: safetensors, regex, pyyaml, fsspec, filelock, huggingface-hub, tokenizers, transformers
Successfully installed filelock-3.17.0 fsspec-2025.3.0 huggingface-hub-0.29.3 pyyaml-6.0.2 regex-2024.11.6 safetensors-0.5.3 tokenizers-0.21.0 transformers-4.49.0
Note: you may need to restart the kernel to use updated packages.

In [5]:
%pip install torch --index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch
  Downloading https://download.pytorch.org/whl/cu121/torch-2.5.1%2Bcu121-cp310-cp310-win_amd64.whl (2449.4 MB)
     ---------------------------------------- 0.0/2.4 GB ? eta -:--:--
     ---------------------------------------- 0.0/2.4 GB 37.6 MB/s eta 0:01:05
     ---------------------------------------- 0.0/2.4 GB 40.9 MB/s eta 0:01:00
     ---------------------------------------- 0.0/2.4 GB 40.8 MB/s eta 0:01:00
      --------------------------------------- 0.0/2.4 GB 42.4 MB/s eta 0:00:57
      --------------------------------------- 0.0/2.4 GB 45.7 MB/s eta 0:00:53
      --------------------------------------- 0.1/2.4 GB 48.2 MB/s eta 0:00:50
     - -------------------------------------- 0.1/2.4 GB 50.9 MB/s eta 0:00:47
     - -------------------------------------- 0.1/2.4 GB 48.9 MB/s eta 0:00:49
     - -------------------------------------- 0.1/2.4 GB 46.5 MB/s eta 0:00:51
     - -------------------------------------- 0.1/2.4 GB 46.6 MB/s eta 0:00:51
     - -------------------------------------- 0.1/2.4 GB 46.0 MB/s eta 0:00:51
     - -------------------------------------- 0.1/2.4 GB 44.0 MB/s eta 0:00:54
     - -------------------------------------- 0.1/2.4 GB 44.1 MB/s eta 0:00:53
     -- ------------------------------------- 0.1/2.4 GB 43.8 MB/s eta 0:00:53
     -- ------------------------------------- 0.1/2.4 GB 43.1 MB/s eta 0:00:54
     -- ------------------------------------- 0.1/2.4 GB 42.8 MB/s eta 0:00:54
     -- ------------------------------------- 0.2/2.4 GB 43.0 MB/s eta 0:00:54
     -- ------------------------------------- 0.2/2.4 GB 42.8 MB/s eta 0:00:54
     -- ------------------------------------- 0.2/2.4 GB 42.8 MB/s eta 0:00:54
     -- ------------------------------------- 0.2/2.4 GB 42.7 MB/s eta 0:00:54
     --- ------------------------------------ 0.2/2.4 GB 42.8 MB/s eta 0:00:53
     --- ------------------------------------ 0.2/2.4 GB 43.0 MB/s eta 0:00:53
     --- ------------------------------------ 0.2/2.4 GB 43.5 MB/s eta 0:00:52
     --- ------------------------------------ 0.2/2.4 GB 43.9 MB/s eta 0:00:51
     --- ------------------------------------ 0.2/2.4 GB 44.2 MB/s eta 0:00:51
     --- ------------------------------------ 0.2/2.4 GB 44.9 MB/s eta 0:00:50
     ---- ----------------------------------- 0.3/2.4 GB 45.5 MB/s eta 0:00:49
     ---- ----------------------------------- 0.3/2.4 GB 46.8 MB/s eta 0:00:47
     ---- ----------------------------------- 0.3/2.4 GB 47.6 MB/s eta 0:00:46
     ---- ----------------------------------- 0.3/2.4 GB 48.7 MB/s eta 0:00:45
     ----- ---------------------------------- 0.3/2.4 GB 49.3 MB/s eta 0:00:44
     ----- ---------------------------------- 0.3/2.4 GB 49.2 MB/s eta 0:00:44
     ----- ---------------------------------- 0.3/2.4 GB 50.6 MB/s eta 0:00:42
     ----- ---------------------------------- 0.4/2.4 GB 51.9 MB/s eta 0:00:41
     ------ --------------------------------- 0.4/2.4 GB 54.8 MB/s eta 0:00:38
     ------ --------------------------------- 0.4/2.4 GB 56.4 MB/s eta 0:00:37
     ------ --------------------------------- 0.4/2.4 GB 59.9 MB/s eta 0:00:35
     ------ --------------------------------- 0.4/2.4 GB 62.5 MB/s eta 0:00:33
     ------- -------------------------------- 0.4/2.4 GB 65.0 MB/s eta 0:00:31
     ------- -------------------------------- 0.5/2.4 GB 67.6 MB/s eta 0:00:30
     ------- -------------------------------- 0.5/2.4 GB 69.0 MB/s eta 0:00:29
     ------- -------------------------------- 0.5/2.4 GB 69.8 MB/s eta 0:00:29
     -------- ------------------------------- 0.5/2.4 GB 71.9 MB/s eta 0:00:28
     -------- ------------------------------- 0.5/2.4 GB 72.6 MB/s eta 0:00:27
     -------- ------------------------------- 0.5/2.4 GB 73.2 MB/s eta 0:00:27
     -------- ------------------------------- 0.5/2.4 GB 73.8 MB/s eta 0:00:26
     --------- ------------------------------ 0.6/2.4 GB 73.2 MB/s eta 0:00:26
     --------- ------------------------------ 0.6/2.4 GB 72.2 MB/s eta 0:00:26
     --------- ------------------------------ 0.6/2.4 GB 70.7 MB/s eta 0:00:27
     --------- ------------------------------ 0.6/2.4 GB 68.7 MB/s eta 0:00:28
     --------- ------------------------------ 0.6/2.4 GB 67.9 MB/s eta 0:00:28
     ---------- ----------------------------- 0.6/2.4 GB 68.1 MB/s eta 0:00:27
     ---------- ----------------------------- 0.6/2.4 GB 68.4 MB/s eta 0:00:27
     ---------- ----------------------------- 0.6/2.4 GB 68.4 MB/s eta 0:00:27
     ---------- ----------------------------- 0.7/2.4 GB 67.6 MB/s eta 0:00:27
     ----------- ---------------------------- 0.7/2.4 GB 67.0 MB/s eta 0:00:27
     ----------- ---------------------------- 0.7/2.4 GB 65.7 MB/s eta 0:00:27
     ----------- ---------------------------- 0.7/2.4 GB 65.5 MB/s eta 0:00:27
     ----------- ---------------------------- 0.7/2.4 GB 64.7 MB/s eta 0:00:27
     ----------- ---------------------------- 0.7/2.4 GB 64.5 MB/s eta 0:00:27
     ------------ --------------------------- 0.7/2.4 GB 64.7 MB/s eta 0:00:27
     ------------ --------------------------- 0.8/2.4 GB 65.0 MB/s eta 0:00:27
     ------------ --------------------------- 0.8/2.4 GB 64.7 MB/s eta 0:00:26
     ------------ --------------------------- 0.8/2.4 GB 64.7 MB/s eta 0:00:26
     ------------- -------------------------- 0.8/2.4 GB 64.5 MB/s eta 0:00:26
     ------------- -------------------------- 0.8/2.4 GB 65.7 MB/s eta 0:00:25
     ------------- -------------------------- 0.8/2.4 GB 64.7 MB/s eta 0:00:26
     ------------- -------------------------- 0.8/2.4 GB 69.3 MB/s eta 0:00:24
     -------------- ------------------------- 0.9/2.4 GB 69.8 MB/s eta 0:00:23
     -------------- ------------------------- 0.9/2.4 GB 70.4 MB/s eta 0:00:23
     -------------- ------------------------- 0.9/2.4 GB 70.7 MB/s eta 0:00:23
     -------------- ------------------------- 0.9/2.4 GB 71.0 MB/s eta 0:00:22
     --------------- ------------------------ 0.9/2.4 GB 70.7 MB/s eta 0:00:22
     --------------- ------------------------ 0.9/2.4 GB 71.0 MB/s eta 0:00:22
     --------------- ------------------------ 1.0/2.4 GB 71.6 MB/s eta 0:00:21
     --------------- ------------------------ 1.0/2.4 GB 71.6 MB/s eta 0:00:21
     ---------------- ----------------------- 1.0/2.4 GB 71.9 MB/s eta 0:00:21
     ---------------- ----------------------- 1.0/2.4 GB 71.9 MB/s eta 0:00:21
     ---------------- ----------------------- 1.0/2.4 GB 71.6 MB/s eta 0:00:21
     ---------------- ----------------------- 1.0/2.4 GB 71.3 MB/s eta 0:00:20
     ---------------- ----------------------- 1.0/2.4 GB 71.0 MB/s eta 0:00:20
     ----------------- ---------------------- 1.1/2.4 GB 70.7 MB/s eta 0:00:20
     ----------------- ---------------------- 1.1/2.4 GB 71.0 MB/s eta 0:00:20
     ----------------- ---------------------- 1.1/2.4 GB 70.4 MB/s eta 0:00:20
     ----------------- ---------------------- 1.1/2.4 GB 71.0 MB/s eta 0:00:20
     ------------------ --------------------- 1.1/2.4 GB 70.7 MB/s eta 0:00:19
     ------------------ --------------------- 1.1/2.4 GB 71.3 MB/s eta 0:00:19
     ------------------ --------------------- 1.2/2.4 GB 71.9 MB/s eta 0:00:19
     ------------------- -------------------- 1.2/2.4 GB 71.9 MB/s eta 0:00:18
     ------------------- -------------------- 1.2/2.4 GB 73.9 MB/s eta 0:00:18
     ------------------- -------------------- 1.2/2.4 GB 73.8 MB/s eta 0:00:17
     ------------------- -------------------- 1.2/2.4 GB 75.2 MB/s eta 0:00:17
     -------------------- ------------------- 1.2/2.4 GB 76.6 MB/s eta 0:00:16
     -------------------- ------------------- 1.3/2.4 GB 76.2 MB/s eta 0:00:16
     -------------------- ------------------- 1.3/2.4 GB 76.2 MB/s eta 0:00:16
     -------------------- ------------------- 1.3/2.4 GB 76.2 MB/s eta 0:00:16
     --------------------- ------------------ 1.3/2.4 GB 76.2 MB/s eta 0:00:16
     --------------------- ------------------ 1.3/2.4 GB 75.8 MB/s eta 0:00:16
     --------------------- ------------------ 1.3/2.4 GB 71.3 MB/s eta 0:00:16
     --------------------- ------------------ 1.3/2.4 GB 71.0 MB/s eta 0:00:16
     --------------------- ------------------ 1.3/2.4 GB 70.1 MB/s eta 0:00:16
     ---------------------- ----------------- 1.3/2.4 GB 69.8 MB/s eta 0:00:16
     ---------------------- ----------------- 1.4/2.4 GB 69.0 MB/s eta 0:00:16
     ---------------------- ----------------- 1.4/2.4 GB 67.9 MB/s eta 0:00:16
     ---------------------- ----------------- 1.4/2.4 GB 67.3 MB/s eta 0:00:16
     ---------------------- ----------------- 1.4/2.4 GB 66.8 MB/s eta 0:00:16
     ----------------------- ---------------- 1.4/2.4 GB 66.2 MB/s eta 0:00:16
     ----------------------- ---------------- 1.4/2.4 GB 65.7 MB/s eta 0:00:16
     ----------------------- ---------------- 1.4/2.4 GB 65.0 MB/s eta 0:00:16
     ----------------------- ---------------- 1.5/2.4 GB 64.5 MB/s eta 0:00:16
     ------------------------ --------------- 1.5/2.4 GB 63.7 MB/s eta 0:00:16
     ------------------------ --------------- 1.5/2.4 GB 63.5 MB/s eta 0:00:16
     ------------------------ --------------- 1.5/2.4 GB 63.2 MB/s eta 0:00:16
     ------------------------ --------------- 1.5/2.4 GB 63.5 MB/s eta 0:00:15
     ------------------------- -------------- 1.5/2.4 GB 63.5 MB/s eta 0:00:15
     ------------------------- -------------- 1.5/2.4 GB 64.0 MB/s eta 0:00:15
     ------------------------- -------------- 1.6/2.4 GB 63.3 MB/s eta 0:00:15
     ------------------------- -------------- 1.6/2.4 GB 67.3 MB/s eta 0:00:13
     ------------------------- -------------- 1.6/2.4 GB 67.3 MB/s eta 0:00:13
     -------------------------- ------------- 1.6/2.4 GB 67.9 MB/s eta 0:00:13
     -------------------------- ------------- 1.6/2.4 GB 69.0 MB/s eta 0:00:13
     -------------------------- ------------- 1.6/2.4 GB 69.8 MB/s eta 0:00:12
     -------------------------- ------------- 1.6/2.4 GB 70.4 MB/s eta 0:00:12
     --------------------------- ------------ 1.7/2.4 GB 70.4 MB/s eta 0:00:12
     --------------------------- ------------ 1.7/2.4 GB 70.4 MB/s eta 0:00:11
     --------------------------- ------------ 1.7/2.4 GB 70.4 MB/s eta 0:00:11
     --------------------------- ------------ 1.7/2.4 GB 68.1 MB/s eta 0:00:11
     --------------------------- ------------ 1.7/2.4 GB 65.7 MB/s eta 0:00:12
     --------------------------- ------------ 1.7/2.4 GB 63.5 MB/s eta 0:00:12
     --------------------------- ------------ 1.7/2.4 GB 61.4 MB/s eta 0:00:13
     ---------------------------- ----------- 1.7/2.4 GB 59.9 MB/s eta 0:00:13
     ---------------------------- ----------- 1.7/2.4 GB 58.2 MB/s eta 0:00:13
     ---------------------------- ----------- 1.7/2.4 GB 57.0 MB/s eta 0:00:13
     ---------------------------- ----------- 1.7/2.4 GB 55.9 MB/s eta 0:00:13
     ---------------------------- ----------- 1.7/2.4 GB 54.2 MB/s eta 0:00:14
     ---------------------------- ----------- 1.7/2.4 GB 52.9 MB/s eta 0:00:14
     ---------------------------- ----------- 1.8/2.4 GB 51.6 MB/s eta 0:00:14
     ---------------------------- ----------- 1.8/2.4 GB 50.5 MB/s eta 0:00:14
     ---------------------------- ----------- 1.8/2.4 GB 49.4 MB/s eta 0:00:14
     ---------------------------- ----------- 1.8/2.4 GB 48.2 MB/s eta 0:00:15
     ----------------------------- ---------- 1.8/2.4 GB 47.2 MB/s eta 0:00:15
     ----------------------------- ---------- 1.8/2.4 GB 46.0 MB/s eta 0:00:15
     ----------------------------- ---------- 1.8/2.4 GB 44.9 MB/s eta 0:00:15
     ----------------------------- ---------- 1.8/2.4 GB 43.9 MB/s eta 0:00:15
     ----------------------------- ---------- 1.8/2.4 GB 43.0 MB/s eta 0:00:16
     ----------------------------- ---------- 1.8/2.4 GB 42.3 MB/s eta 0:00:16
     ----------------------------- ---------- 1.8/2.4 GB 41.7 MB/s eta 0:00:16
     ----------------------------- ---------- 1.8/2.4 GB 41.7 MB/s eta 0:00:15
     ------------------------------ --------- 1.8/2.4 GB 41.3 MB/s eta 0:00:15
     ------------------------------ --------- 1.8/2.4 GB 40.7 MB/s eta 0:00:15
     ------------------------------ --------- 1.9/2.4 GB 40.3 MB/s eta 0:00:15
     ------------------------------ --------- 1.9/2.4 GB 39.8 MB/s eta 0:00:15
     ------------------------------ --------- 1.9/2.4 GB 39.6 MB/s eta 0:00:15
     ------------------------------- -------- 1.9/2.4 GB 39.7 MB/s eta 0:00:14
     ------------------------------- -------- 1.9/2.4 GB 39.7 MB/s eta 0:00:14
     ------------------------------- -------- 1.9/2.4 GB 39.7 MB/s eta 0:00:14
     ------------------------------- -------- 1.9/2.4 GB 39.7 MB/s eta 0:00:13
     -------------------------------- ------- 2.0/2.4 GB 41.7 MB/s eta 0:00:12
     -------------------------------- ------- 2.0/2.4 GB 44.7 MB/s eta 0:00:11
     -------------------------------- ------- 2.0/2.4 GB 46.9 MB/s eta 0:00:10
     -------------------------------- ------- 2.0/2.4 GB 49.4 MB/s eta 0:00:09
     -------------------------------- ------- 2.0/2.4 GB 51.4 MB/s eta 0:00:09
     --------------------------------- ------ 2.0/2.4 GB 51.9 MB/s eta 0:00:09
     --------------------------------- ------ 2.0/2.4 GB 53.7 MB/s eta 0:00:08
     --------------------------------- ------ 2.1/2.4 GB 57.4 MB/s eta 0:00:07
     --------------------------------- ------ 2.1/2.4 GB 60.5 MB/s eta 0:00:07
     --------------------------------- ------ 2.1/2.4 GB 61.4 MB/s eta 0:00:07
     ---------------------------------- ----- 2.1/2.4 GB 63.2 MB/s eta 0:00:06
     ---------------------------------- ----- 2.1/2.4 GB 64.0 MB/s eta 0:00:06
     ---------------------------------- ----- 2.1/2.4 GB 65.7 MB/s eta 0:00:06
     ---------------------------------- ----- 2.1/2.4 GB 66.8 MB/s eta 0:00:05
     ----------------------------------- ---- 2.2/2.4 GB 67.0 MB/s eta 0:00:05
     ----------------------------------- ---- 2.2/2.4 GB 67.0 MB/s eta 0:00:05
     ----------------------------------- ---- 2.2/2.4 GB 66.8 MB/s eta 0:00:04
     ----------------------------------- ---- 2.2/2.4 GB 66.2 MB/s eta 0:00:04
     ------------------------------------ --- 2.2/2.4 GB 65.0 MB/s eta 0:00:04
     ------------------------------------ --- 2.2/2.4 GB 65.0 MB/s eta 0:00:04
     ------------------------------------ --- 2.2/2.4 GB 64.5 MB/s eta 0:00:04
     ------------------------------------ --- 2.2/2.4 GB 63.5 MB/s eta 0:00:04
     ------------------------------------ --- 2.3/2.4 GB 63.2 MB/s eta 0:00:04
     ------------------------------------- -- 2.3/2.4 GB 63.0 MB/s eta 0:00:03
     ------------------------------------- -- 2.3/2.4 GB 63.0 MB/s eta 0:00:03
     ------------------------------------- -- 2.3/2.4 GB 61.4 MB/s eta 0:00:03
     ------------------------------------- -- 2.3/2.4 GB 62.5 MB/s eta 0:00:03
     ------------------------------------- -- 2.3/2.4 GB 63.3 MB/s eta 0:00:03
     -------------------------------------- - 2.3/2.4 GB 63.2 MB/s eta 0:00:02
     -------------------------------------- - 2.3/2.4 GB 63.3 MB/s eta 0:00:02
     -------------------------------------- - 2.4/2.4 GB 62.5 MB/s eta 0:00:02
     -------------------------------------- - 2.4/2.4 GB 62.8 MB/s eta 0:00:02
     -------------------------------------- - 2.4/2.4 GB 63.0 MB/s eta 0:00:02
     ---------------------------------------  2.4/2.4 GB 63.0 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 62.8 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 62.3 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 61.2 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------  2.4/2.4 GB 60.5 MB/s eta 0:00:01
     ---------------------------------------- 2.4/2.4 GB 35.4 MB/s eta 0:00:00
Requirement already satisfied: filelock in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from torch) (4.12.2)
Collecting networkx (from torch)
  Downloading https://download.pytorch.org/whl/networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Collecting jinja2 (from torch)
  Downloading https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: fsspec in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from torch) (2025.3.0)
Collecting sympy==1.13.1 (from torch)
  Downloading https://download.pytorch.org/whl/sympy-1.13.1-py3-none-any.whl (6.2 MB)
     ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
     ---------------------------------------- 6.2/6.2 MB 42.0 MB/s eta 0:00:00
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch)
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Downloading https://download.pytorch.org/whl/MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
Downloading https://download.pytorch.org/whl/Jinja2-3.1.4-py3-none-any.whl (133 kB)
Downloading https://download.pytorch.org/whl/networkx-3.3-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 46.5 MB/s eta 0:00:00
Installing collected packages: mpmath, sympy, networkx, MarkupSafe, jinja2, torch
Successfully installed MarkupSafe-2.1.5 jinja2-3.1.4 mpmath-1.3.0 networkx-3.3 sympy-1.13.1 torch-2.5.1+cu121
Note: you may need to restart the kernel to use updated packages.

In [31]:
%pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.6.1-cp310-cp310-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: numpy>=1.19.5 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from scikit-learn) (2.2.2)
Collecting scipy>=1.6.0 (from scikit-learn)
  Downloading scipy-1.15.2-cp310-cp310-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.6.1-cp310-cp310-win_amd64.whl (11.1 MB)
Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
Downloading scipy-1.15.2-cp310-cp310-win_amd64.whl (41.2 MB)
   ---------------------------------------- 0.0/41.2 MB ? eta -:--:--
   ---------- ----------------------------- 10.5/41.2 MB 50.4 MB/s eta 0:00:01
   ------------------- -------------------- 20.2/41.2 MB 49.1 MB/s eta 0:00:01
   ---------------------------- ----------- 29.1/41.2 MB 46.1 MB/s eta 0:00:01
   ----------------------------------- ---- 36.4/41.2 MB 42.9 MB/s eta 0:00:01
   ---------------------------------------  41.2/41.2 MB 42.2 MB/s eta 0:00:01
   ---------------------------------------- 41.2/41.2 MB 37.5 MB/s eta 0:00:00
Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn
Successfully installed joblib-1.4.2 scikit-learn-1.6.1 scipy-1.15.2 threadpoolctl-3.5.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import csv

from transformers import pipeline
# import plotly as plt
from tqdm import tqdm
import plotly.express as px
import pandas as pd
from sklearn.decomposition import PCA

c:\Users\trraa\Documents\repos\civic-dashboard\.venv\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
clf = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")

Device set to use cuda:0

In [ ]:
# Answering a question by garo
result = clf("assault", ['crime', 'safety', 'climate'], multi_label=True)
result

{'sequence': 'assault',
 'labels': ['crime', 'climate', 'safety'],
 'scores': [0.9970975518226624, 0.06776425242424011, 0.00011305409134365618]}

In [7]:
seq = "hello world!"
candidate_labels = ["greeting", "food"]
result = clf(seq, candidate_labels, multi_label=True)
result

{'sequence': 'hello world!',
 'labels': ['greeting', 'food'],
 'scores': [0.9980689883232117, 0.006720312405377626]}

In [2]:
filename = 'all_items/comma_separated_subject_terms_unique.txt'
subject_terms = []
with open(filename, 'r', encoding='utf-8') as file:
    subject_terms = file.readlines()
subject_terms = [term.strip() for term in subject_terms]
subject_terms[:5]

['20-minute makeover', '25 year club', '3 R', '3-1-1', '311']

In [28]:
categories = 'housing', 'bikes', 'homelessness', 'dogs', 'parks', 'construction', \
    'traffic', 'transit', 'noise', 'energy', 'climate', 'infrastructure', 'safety', \
    'arts', 'childcare', 'democracy', 'cost of living', 'healthcare', 'equity', 'business'

In [27]:
seq = "3-1-1"
candidate_labels = categories
result = clf(subject_terms[:100], candidate_labels, multi_label=True)
result

[{'sequence': '20-minute makeover',
  'labels': ['housing',
   'arts',
   'energy',
   'infrastructure',
   'transit',
   'healthcare',
   'business',
   'equity',
   'parks',
   'climate',
   'safety',
   'democracy',
   'bikes',
   'cost of living',
   'traffic',
   'construction',
   'childcare',
   'dogs',
   'noise',
   'homelessness'],
  'scores': [0.5942015647888184,
   0.5228010416030884,
   0.3656248450279236,
   0.3273620009422302,
   0.31905341148376465,
   0.2989250123500824,
   0.27293574810028076,
   0.25690945982933044,
   0.2551889419555664,
   0.17421387135982513,
   0.14233194291591644,
   0.111852265894413,
   0.10765796154737473,
   0.09245359152555466,
   0.07810419797897339,
   0.045479025691747665,
   0.04260934144258499,
   0.014990188181400299,
   0.00776075990870595,
   0.006135446019470692]},
 {'sequence': '25 year club',
  'labels': ['equity',
   'business',
   'housing',
   'arts',
   'transit',
   'construction',
   'energy',
   'parks',
   'healthcare',
   'climate',
   'infrastructure',
   'safety',
   'bikes',
   'traffic',
   'cost of living',
   'democracy',
   'childcare',
   'dogs',
   'noise',
   'homelessness'],
  'scores': [0.4595496654510498,
   0.3890904486179352,
   0.3641347885131836,
   0.2821906507015228,
   0.2313966602087021,
   0.1969018578529358,
   0.19234269857406616,
   0.1884489506483078,
   0.16815370321273804,
   0.1299300193786621,
   0.11008647829294205,
   0.07891956716775894,
   0.03737521916627884,
   0.027482133358716965,
   0.026408353820443153,
   0.016692552715539932,
   0.01256514247506857,
   0.011490010656416416,
   0.000819978944491595,
   0.0001236644311575219]},
 {'sequence': '3 R',
  'labels': ['cost of living',
   'transit',
   'business',
   'energy',
   'arts',
   'housing',
   'safety',
   'construction',
   'infrastructure',
   'equity',
   'bikes',
   'climate',
   'healthcare',
   'traffic',
   'parks',
   'childcare',
   'noise',
   'homelessness',
   'dogs',
   'democracy'],
  'scores': [0.6441783905029297,
   0.5830466747283936,
   0.5525677800178528,
   0.5449357032775879,
   0.5037031769752502,
   0.4808206260204315,
   0.45810917019844055,
   0.42274048924446106,
   0.40875470638275146,
   0.3874093294143677,
   0.31441909074783325,
   0.2701929211616516,
   0.2559577226638794,
   0.24229668080806732,
   0.20497606694698334,
   0.1529100239276886,
   0.09347018599510193,
   0.07828326523303986,
   0.04188205301761627,
   0.004229116719216108]},
 {'sequence': '3-1-1',
  'labels': ['transit',
   'business',
   'housing',
   'safety',
   'arts',
   'construction',
   'energy',
   'infrastructure',
   'equity',
   'cost of living',
   'traffic',
   'climate',
   'healthcare',
   'parks',
   'childcare',
   'noise',
   'bikes',
   'homelessness',
   'democracy',
   'dogs'],
  'scores': [0.6746253371238708,
   0.626048743724823,
   0.6031783819198608,
   0.5907905697822571,
   0.577592134475708,
   0.5733604431152344,
   0.5314455628395081,
   0.5048217177391052,
   0.4746744930744171,
   0.45469632744789124,
   0.393126517534256,
   0.3794704079627991,
   0.33236461877822876,
   0.2684726417064667,
   0.25087428092956543,
   0.12763716280460358,
   0.11839210242033005,
   0.10184977948665619,
   0.08784538507461548,
   0.04039691388607025]},
 {'sequence': '311',
  'labels': ['business',
   'transit',
   'housing',
   'cost of living',
   'arts',
   'safety',
   'infrastructure',
   'energy',
   'construction',
   'equity',
   'traffic',
   'healthcare',
   'climate',
   'parks',
   'homelessness',
   'childcare',
   'democracy',
   'bikes',
   'noise',
   'dogs'],
  'scores': [0.4880109429359436,
   0.4609909653663635,
   0.4190574288368225,
   0.4002126455307007,
   0.38828378915786743,
   0.3716129958629608,
   0.3586510717868805,
   0.34026044607162476,
   0.2972612679004669,
   0.29495498538017273,
   0.22500479221343994,
   0.2077641785144806,
   0.20181867480278015,
   0.13574999570846558,
   0.10926724225282669,
   0.10602981597185135,
   0.09583765268325806,
   0.0818675309419632,
   0.0742359608411789,
   0.03862560912966728]},
 {'sequence': '311 calls',
  'labels': ['transit',
   'business',
   'infrastructure',
   'safety',
   'traffic',
   'energy',
   'housing',
   'equity',
   'construction',
   'healthcare',
   'noise',
   'climate',
   'arts',
   'cost of living',
   'parks',
   'childcare',
   'homelessness',
   'democracy',
   'bikes',
   'dogs'],
  'scores': [0.4139636754989624,
   0.39946550130844116,
   0.34416070580482483,
   0.3189408481121063,
   0.2330915927886963,
   0.18594589829444885,
   0.16408655047416687,
   0.16342106461524963,
   0.16077862679958344,
   0.13305868208408356,
   0.11929687112569809,
   0.09548559784889221,
   0.07404770702123642,
   0.07132230699062347,
   0.048866745084524155,
   0.03994766250252724,
   0.0322878472507,
   0.013638678006827831,
   0.009836754761636257,
   0.00889293197542429]},
 {'sequence': '9-1-1',
  'labels': ['safety',
   'transit',
   'business',
   'equity',
   'infrastructure',
   'arts',
   'construction',
   'housing',
   'energy',
   'cost of living',
   'healthcare',
   'traffic',
   'climate',
   'parks',
   'noise',
   'childcare',
   'homelessness',
   'bikes',
   'democracy',
   'dogs'],
  'scores': [0.5758204460144043,
   0.4785614013671875,
   0.4102899432182312,
   0.3276629149913788,
   0.32407718896865845,
   0.2924661338329315,
   0.29101797938346863,
   0.2909964323043823,
   0.28250911831855774,
   0.2319575995206833,
   0.18927918374538422,
   0.12396100908517838,
   0.12329576164484024,
   0.09607395529747009,
   0.08349615335464478,
   0.0708855539560318,
   0.068949393928051,
   0.033961258828639984,
   0.025256482884287834,
   0.014960519038140774]},
 {'sequence': '911',
  'labels': ['safety',
   'cost of living',
   'transit',
   'noise',
   'equity',
   'infrastructure',
   'business',
   'climate',
   'housing',
   'construction',
   'traffic',
   'energy',
   'homelessness',
   'parks',
   'arts',
   'bikes',
   'childcare',
   'healthcare',
   'dogs',
   'democracy'],
  'scores': [0.9168259501457214,
   0.22263507544994354,
   0.19929662346839905,
   0.15666714310646057,
   0.12837162613868713,
   0.09494806826114655,
   0.09332814812660217,
   0.07981648296117783,
   0.06498664617538452,
   0.05236678197979927,
   0.04308880865573883,
   0.042785294353961945,
   0.028505615890026093,
   0.019045129418373108,
   0.011020985431969166,
   0.00836633425205946,
   0.00601612264290452,
   0.004492912907153368,
   0.0042105563916265965,
   0.0006585886585526168]},
 {'sequence': '911 calls',
  'labels': ['safety',
   'equity',
   'noise',
   'transit',
   'traffic',
   'infrastructure',
   'homelessness',
   'cost of living',
   'business',
   'housing',
   'climate',
   'dogs',
   'democracy',
   'construction',
   'energy',
   'healthcare',
   'bikes',
   'parks',
   'arts',
   'childcare'],
  'scores': [0.9127578735351562,
   0.0414491668343544,
   0.026236582547426224,
   0.008162658661603928,
   0.0022293408401310444,
   0.0018532120157033205,
   0.0016971646109595895,
   0.001408668584190309,
   0.0011205367045477033,
   0.0010926045943051577,
   0.0007966060657054186,
   0.0005840721423737705,
   0.0004169617313891649,
   0.0003425177710596472,
   0.0003347777237650007,
   0.0002155414695153013,
   0.0002098771365126595,
   0.00018945122428704053,
   0.00017112480418290943,
   0.00014081680274102837]},
 {'sequence': 'AED',
  'labels': ['healthcare',
   'energy',
   'safety',
   'infrastructure',
   'cost of living',
   'business',
   'arts',
   'construction',
   'housing',
   'transit',
   'climate',
   'parks',
   'equity',
   'traffic',
   'democracy',
   'dogs',
   'childcare',
   'bikes',
   'homelessness',
   'noise'],
  'scores': [0.971057653427124,
   0.964066743850708,
   0.9520189762115479,
   0.7692595720291138,
   0.699804961681366,
   0.436053603887558,
   0.4326359033584595,
   0.13960492610931396,
   0.11472034454345703,
   0.08909980952739716,
   0.07226879894733429,
   0.05311042442917824,
   0.029816096648573875,
   0.02890286222100258,
   0.014249072410166264,
   0.00834893248975277,
   0.007352590560913086,
   0.004164377227425575,
   0.003576224436983466,
   0.00023180969583336264]},
 {'sequence': 'AEI',
  'labels': ['arts',
   'equity',
   'energy',
   'business',
   'safety',
   'healthcare',
   'infrastructure',
   'transit',
   'construction',
   'cost of living',
   'housing',
   'climate',
   'traffic',
   'democracy',
   'parks',
   'childcare',
   'bikes',
   'homelessness',
   'dogs',
   'noise'],
  'scores': [0.9422327876091003,
   0.9146770238876343,
   0.7588959336280823,
   0.508641242980957,
   0.46648460626602173,
   0.29962724447250366,
   0.2842719852924347,
   0.24863164126873016,
   0.1872480809688568,
   0.18284305930137634,
   0.10399545729160309,
   0.07610490173101425,
   0.06415538489818573,
   0.038410503417253494,
   0.03664599359035492,
   0.03130891174077988,
   0.022378811612725258,
   0.015121744014322758,
   0.011507127434015274,
   0.0031782689038664103]},
 {'sequence': 'AIDS',
  'labels': ['transit',
   'housing',
   'parks',
   'noise',
   'construction',
   'healthcare',
   'cost of living',
   'traffic',
   'safety',
   'dogs',
   'bikes',
   'arts',
   'equity',
   'infrastructure',
   'business',
   'homelessness',
   'energy',
   'childcare',
   'climate',
   'democracy'],
  'scores': [0.020715326070785522,
   0.008072136901319027,
   0.0016269786283373833,
   0.0012001304421573877,
   0.0011487562442198396,
   0.0009245580877177417,
   0.0006835070671513677,
   0.0005863552796654403,
   0.0005726004601456225,
   0.0005001853569410741,
   0.0003883024037349969,
   0.0003389251069165766,
   0.00033186684595420957,
   0.0002815587795339525,
   0.0002533797814976424,
   0.00024391616170760244,
   0.00017570254567544907,
   0.00017000566003844142,
   0.00016129652794916183,
   6.649339775322005e-05]},
 {'sequence': 'ALH',
  'labels': ['equity',
   'energy',
   'arts',
   'safety',
   'healthcare',
   'cost of living',
   'business',
   'housing',
   'transit',
   'infrastructure',
   'construction',
   'climate',
   'traffic',
   'childcare',
   'parks',
   'noise',
   'homelessness',
   'bikes',
   'democracy',
   'dogs'],
  'scores': [0.9079126715660095,
   0.8318269848823547,
   0.6060125231742859,
   0.49162864685058594,
   0.44601696729660034,
   0.43284714221954346,
   0.39506760239601135,
   0.37245604395866394,
   0.32719579339027405,
   0.2487664520740509,
   0.22665652632713318,
   0.14112944900989532,
   0.10204994678497314,
   0.09076858311891556,
   0.06537564098834991,
   0.05761469900608063,
   0.055090196430683136,
   0.031181909143924713,
   0.025805504992604256,
   0.01551580335944891]},
 {'sequence': 'APS',
  'labels': ['arts',
   'safety',
   'energy',
   'cost of living',
   'business',
   'housing',
   'infrastructure',
   'transit',
   'construction',
   'equity',
   'parks',
   'healthcare',
   'climate',
   'traffic',
   'childcare',
   'homelessness',
   'bikes',
   'democracy',
   'dogs',
   'noise'],
  'scores': [0.9544917345046997,
   0.6233181357383728,
   0.5036972165107727,
   0.43864932656288147,
   0.3559568524360657,
   0.2694655954837799,
   0.2638503313064575,
   0.2573358714580536,
   0.23109690845012665,
   0.1897510439157486,
   0.1870194524526596,
   0.17554950714111328,
   0.11660811305046082,
   0.08558324724435806,
   0.0760432705283165,
   0.04950673505663872,
   0.04589879885315895,
   0.03353046998381615,
   0.02780129574239254,
   0.020574621856212616]},
 {'sequence': 'AQHI',
  'labels': ['healthcare',
   'housing',
   'energy',
   'business',
   'infrastructure',
   'safety',
   'cost of living',
   'arts',
   'construction',
   'equity',
   'transit',
   'climate',
   'traffic',
   'parks',
   'childcare',
   'bikes',
   'dogs',
   'noise',
   'homelessness',
   'democracy'],
  'scores': [0.7398441433906555,
   0.5223784446716309,
   0.4131466746330261,
   0.300813227891922,
   0.17727769911289215,
   0.15178106725215912,
   0.13824020326137543,
   0.12424669414758682,
   0.08080605417490005,
   0.06955306977033615,
   0.05357428267598152,
   0.044858016073703766,
   0.011548342183232307,
   0.009895904920995235,
   0.006039861124008894,
   0.003124422626569867,
   0.0024963205214589834,
   0.0021658020559698343,
   0.0020456251222640276,
   0.0010239235125482082]},
 {'sequence': 'AQI',
  'labels': ['equity',
   'energy',
   'infrastructure',
   'safety',
   'cost of living',
   'transit',
   'arts',
   'business',
   'housing',
   'construction',
   'climate',
   'parks',
   'traffic',
   'healthcare',
   'childcare',
   'homelessness',
   'bikes',
   'dogs',
   'democracy',
   'noise'],
  'scores': [0.8025246262550354,
   0.3957846462726593,
   0.2803393304347992,
   0.14328032732009888,
   0.1143922358751297,
   0.1081082746386528,
   0.07365074753761292,
   0.07193002104759216,
   0.07083391398191452,
   0.062330424785614014,
   0.0438082180917263,
   0.03862552344799042,
   0.03395423665642738,
   0.03130946680903435,
   0.013256928883492947,
   0.008794994093477726,
   0.006417213939130306,
   0.0061248308047652245,
   0.004088667221367359,
   0.0017302037449553609]},
 {'sequence': 'ATMs',
  'labels': ['infrastructure',
   'business',
   'safety',
   'cost of living',
   'transit',
   'equity',
   'climate',
   'arts',
   'energy',
   'noise',
   'democracy',
   'healthcare',
   'construction',
   'traffic',
   'housing',
   'bikes',
   'dogs',
   'childcare',
   'parks',
   'homelessness'],
  'scores': [0.9678306579589844,
   0.8081809282302856,
   0.7777783274650574,
   0.0036743064410984516,
   0.003444804809987545,
   0.0025844054762274027,
   0.00047683139564469457,
   0.00046143538202159107,
   0.000358568096999079,
   0.00027176798903383315,
   0.00021529782679863274,
   0.00016408944793511182,
   0.00014263458433561027,
   0.00011822958913398907,
   8.235493442043662e-05,
   7.945828838273883e-05,
   7.174584607128054e-05,
   6.333927740342915e-05,
   6.154588481876999e-05,
   5.934865475865081e-05]},
 {'sequence': 'Acquired Immunodeficiency Syndrome',
  'labels': ['healthcare',
   'transit',
   'parks',
   'housing',
   'dogs',
   'infrastructure',
   'childcare',
   'equity',
   'safety',
   'traffic',
   'bikes',
   'energy',
   'climate',
   'business',
   'arts',
   'construction',
   'noise',
   'cost of living',
   'democracy',
   'homelessness'],
  'scores': [0.11082630604505539,
   0.03172117471694946,
   0.025823500007390976,
   0.014468924142420292,
   0.002869454910978675,
   0.0018050346989184618,
   0.0015360887628048658,
   0.00134676368907094,
   0.0011313188588246703,
   0.0010000111069530249,
   0.0008332128636538982,
   0.0007305062026716769,
   0.0005674160784110427,
   0.0004834962892346084,
   0.0004665506712626666,
   0.0003491098468657583,
   0.00027985862107016146,
   0.0002575040271040052,
   0.00014163060404825956,
   0.0001398417807649821]},
 {'sequence': 'Alzheimers',
  'labels': ['housing',
   'transit',
   'noise',
   'healthcare',
   'safety',
   'equity',
   'parks',
   'traffic',
   'cost of living',
   'energy',
   'climate',
   'infrastructure',
   'construction',
   'business',
   'dogs',
   'arts',
   'bikes',
   'homelessness',
   'childcare',
   'democracy'],
  'scores': [0.003254687413573265,
   0.0017450394807383418,
   0.0014164225431159139,
   0.001117574400268495,
   0.0007684165029786527,
   0.0006320055690594018,
   0.0006043157773092389,
   0.0002954843221232295,
   0.00025162778911180794,
   0.00022484087094198912,
   0.00021619365725200623,
   0.00019696952949743718,
   0.0001777427678462118,
   0.00016522197984158993,
   0.00016122360830195248,
   0.00014913425548002124,
   0.00012941539171151817,
   6.779703835491091e-05,
   6.694666080875322e-05,
   5.5197422625496984e-05]},
 {'sequence': 'Asian Long Horned Beetles',
  'labels': ['energy',
   'transit',
   'equity',
   'arts',
   'safety',
   'parks',
   'business',
   'housing',
   'cost of living',
   'construction',
   'noise',
   'climate',
   'infrastructure',
   'childcare',
   'healthcare',
   'democracy',
   'homelessness',
   'traffic',
   'bikes',
   'dogs'],
  'scores': [0.6077945232391357,
   0.49090662598609924,
   0.3653514087200165,
   0.3084815740585327,
   0.2142072468996048,
   0.1081644669175148,
   0.061379898339509964,
   0.059211891144514084,
   0.020466139540076256,
   0.016067391261458397,
   0.009512996301054955,
   0.006813954096287489,
   0.006265633273869753,
   0.004762053024023771,
   0.00345734809525311,
   0.003230659756809473,
   0.0020405210088938475,
   0.001422451576218009,
   0.0001684938615653664,
   9.225283429259434e-05]},
 {'sequence': 'Asian Long-Horned Beetles',
  'labels': ['energy',
   'transit',
   'equity',
   'arts',
   'safety',
   'parks',
   'business',
   'housing',
   'construction',
   'cost of living',
   'noise',
   'childcare',
   'healthcare',
   'infrastructure',
   'climate',
   'democracy',
   'homelessness',
   'traffic',
   'bikes',
   'dogs'],
  'scores': [0.5453331470489502,
   0.5312153697013855,
   0.32675522565841675,
   0.30832305550575256,
   0.25214412808418274,
   0.07592075318098068,
   0.061105117201805115,
   0.04370979219675064,
   0.015446132980287075,
   0.009899881668388844,
   0.0052988664247095585,
   0.005134319420903921,
   0.003691701451316476,
   0.0030730327125638723,
   0.0021584874484688044,
   0.0021557407453656197,
   0.0011871174210682511,
   0.0008574086823500693,
   0.00013570152805186808,
   7.979103247635067e-05]},
 {'sequence': 'Asian Longhorned Beetles',
  'labels': ['transit',
   'energy',
   'equity',
   'arts',
   'safety',
   'housing',
   'business',
   'parks',
   'climate',
   'cost of living',
   'construction',
   'childcare',
   'healthcare',
   'noise',
   'infrastructure',
   'democracy',
   'homelessness',
   'traffic',
   'bikes',
   'dogs'],
  'scores': [0.5277848243713379,
   0.4840465486049652,
   0.4461086690425873,
   0.35892942547798157,
   0.2715804874897003,
   0.14081944525241852,
   0.10856133699417114,
   0.10810329020023346,
   0.03616204857826233,
   0.02668941766023636,
   0.023805009201169014,
   0.011685213074088097,
   0.008397859521210194,
   0.007800592575222254,
   0.006884274072945118,
   0.005544984247535467,
   0.0017235464183613658,
   0.0010277460096403956,
   0.00015174029977060854,
   8.291685662698e-05]},
 {'sequence': 'Avenues',
  'labels': ['infrastructure',
   'safety',
   'traffic',
   'transit',
   'equity',
   'business',
   'cost of living',
   'democracy',
   'construction',
   'housing',
   'arts',
   'energy',
   'bikes',
   'climate',
   'dogs',
   'healthcare',
   'noise',
   'childcare',
   'parks',
   'homelessness'],
  'scores': [0.9394447207450867,
   0.40705734491348267,
   0.20018018782138824,
   0.017542904242873192,
   0.01708274520933628,
   0.007122798357158899,
   0.0065573034808039665,
   0.003920815419405699,
   0.001632864703424275,
   0.001255034003406763,
   0.0009323420817963779,
   0.0008583852904848754,
   0.0008266973891295493,
   0.0005365050164982677,
   0.0004863991343881935,
   0.0004684296145569533,
   0.0004403334460221231,
   0.00033084797905758023,
   0.00028511250275187194,
   0.0001614430802874267]},
 {'sequence': 'BIA',
  'labels': ['business',
   'bikes',
   'infrastructure',
   'safety',
   'cost of living',
   'energy',
   'construction',
   'equity',
   'housing',
   'transit',
   'healthcare',
   'arts',
   'climate',
   'traffic',
   'parks',
   'democracy',
   'homelessness',
   'dogs',
   'childcare',
   'noise'],
  'scores': [0.9919129014015198,
   0.988265872001648,
   0.9316254258155823,
   0.3781493306159973,
   0.2492561787366867,
   0.1836714744567871,
   0.1424136608839035,
   0.10507438331842422,
   0.09160204231739044,
   0.07532023638486862,
   0.07252562791109085,
   0.06211153790354729,
   0.05506051331758499,
   0.031014053151011467,
   0.025859564542770386,
   0.012311755679547787,
   0.010515556670725346,

In [28]:
dict(zip(result[0]['labels'], result[0]['scores']))

{'housing': 0.5942015647888184,
 'arts': 0.5228010416030884,
 'energy': 0.3656248450279236,
 'infrastructure': 0.3273620009422302,
 'transit': 0.31905341148376465,
 'healthcare': 0.2989250123500824,
 'business': 0.27293574810028076,
 'equity': 0.25690945982933044,
 'parks': 0.2551889419555664,
 'climate': 0.17421387135982513,
 'safety': 0.14233194291591644,
 'democracy': 0.111852265894413,
 'bikes': 0.10765796154737473,
 'cost of living': 0.09245359152555466,
 'traffic': 0.07810419797897339,
 'construction': 0.045479025691747665,
 'childcare': 0.04260934144258499,
 'dogs': 0.014990188181400299,
 'noise': 0.00776075990870595,
 'homelessness': 0.006135446019470692}

In [64]:
# Compute similarities

filename = 'all_items/similarities.csv'
with open(filename, 'w', newline='', encoding='utf-8') as file:
    writer = csv.DictWriter(file, fieldnames=['subject_term'] + list(categories))
    writer.writeheader()

    batch_index = 0
    batch_size = 50
    progress = tqdm(total=len(subject_terms))
    while batch_index * batch_size <= len(subject_terms):
    # for term in tqdm(subject_terms[:100]):
        curr_term_batch = subject_terms[batch_index * batch_size:(batch_index + 1) * batch_size]
        results = clf(curr_term_batch, categories, multi_label=True)
        output = []
        for result in results:
            row = dict(zip(result['labels'], result['scores']))
            row['subject_term'] = result['sequence']
            output.append(row)
        
        writer.writerows(output)
        progress.update(batch_size)
        batch_index += 1
    progress.close()

5000it [44:59,  1.85it/s]

In [2]:
def reduce_dimensionality(df: pd.DataFrame, num_dimensions: int) -> pd.DataFrame:
    pca = PCA(n_components=num_dimensions)
    pca.fit(df)
    reduced_df = pd.DataFrame(pca.transform(df))
    return reduced_df

In [23]:
df = pd.read_csv('all_items/similarities.csv')
df['max_val'] = df.drop(columns=['subject_term']).max(axis=1)
df['max_cat'] = df.drop(columns=['subject_term']).idxmax(axis=1)
# df

In [31]:
# Add subject term frequency
from collections import Counter
import numpy as np

subject_term_counter = Counter()
with open("all_items/comma_separated_subject_terms.txt", 'r', encoding='utf-8') as file:
    for line in file:
        term = line.strip()
        subject_term_counter[term] += 1

df['frequency'] = 0
frequencies = []
for i, row in df.iterrows():
    frequencies.append(subject_term_counter[row['subject_term']])
df['frequency'] = frequencies
assert df['frequency'].all()

df['log_frequency'] = np.log(df['frequency'])
df

,subject_term,housing,bikes,homelessness,dogs,parks,construction,traffic,transit,noise,...,childcare,democracy,cost of living,healthcare,equity,business,max_val,max_cat,frequency,log_frequency
0,20-minute makeover,0.594202,0.107658,0.006135,0.014990,0.255189,0.045479,0.078104,0.319053,0.007761,...,0.042609,0.111852,0.092454,0.298925,0.256909,0.272936,0.594202,housing,56,4.025352
1,25 year club,0.364135,0.037375,0.000124,0.011490,0.188449,0.196902,0.027482,0.231397,0.000820,...,0.012565,0.016693,0.026408,0.168154,0.459550,0.389090,0.459550,equity,37,3.610918
2,3 R,0.480821,0.314419,0.078283,0.041882,0.204976,0.422740,0.242297,0.583047,0.093470,...,0.152910,0.004229,0.644178,0.255958,0.387409,0.552568,0.644178,cost of living,41,3.713572
3,3-1-1,0.603178,0.118392,0.101850,0.040397,0.268473,0.573360,0.393127,0.674625,0.127637,...,0.250874,0.087845,0.454696,0.332365,0.474674,0.626049,0.674625,transit,26,3.258097
4,311,0.419057,0.081868,0.109267,0.038626,0.135750,0.297261,0.225005,0.460991,0.074236,...,0.106030,0.095838,0.400213,0.207764,0.294955,0.488011,0.488011,business,26,3.258097
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4958,zoning bylaws,0.302043,0.007835,0.000503,0.005450,0.000857,0.012403,0.000306,0.001429,0.000875,...,0.000920,0.000226,0.000318,0.000089,0.004238,0.031259,0.302043,housing,2187,7.690286
4959,zoning designations,0.194599,0.004760,0.000661,0.001801,0.004201,0.002165,0.000906,0.008502,0.000357,...,0.000989,0.000764,0.000794,0.000765,0.004791,0.018773,0.194599,housing,120,4.787492
4960,zoning project,0.055261,0.001287,0.000158,0.000950,0.000836,0.152740,0.000422,0.001569,0.000564,...,0.000099,0.000534,0.000851,0.000157,0.007242,0.085508,0.152740,construction,2187,7.690286
4961,zoo animals,0.000352,0.000078,0.000046,0.004680,0.006998,0.000107,0.000087,0.003130,0.000293,...,0.000091,0.000104,0.000313,0.000081,0.003158,0.000233,0.006998,parks,48,3.871201
4962,zoos,0.041261,0.003561,0.033976,0.995291,0.013428,0.092841,0.029663,0.329301,0.241722,...,0.055178,0.005333,0.145248,0.067034,0.022508,0.096183,0.995291,dogs,425,6.052089

In [ ]:
reduced_df = pd.DataFrame(df)
reduced_df.drop(columns=['subject_term', 'max_val', 'max_cat'], inplace=True)
reduced_df = reduce_dimensionality(reduced_df, 3)
reduced_df.insert(0, 'subject_term', pd.Series(df['subject_term']))
reduced_df

             subject_term         0         1         2
0      20-minute makeover  0.315362  0.238471  0.541400
1            25 year club  0.094327  0.346151  0.313299
2                     3 R  0.937087  0.361039  0.678909
3                   3-1-1  1.202609  0.357450  0.752502
4                     311  0.652740  0.270811  0.451131
...                   ...       ...       ...       ...
4958        zoning bylaws -0.400941  0.013335  0.107570
4959  zoning designations -0.412990 -0.032292  0.058304
4960       zoning project -0.387252  0.015264 -0.021955
4961          zoo animals -0.468755 -0.082855 -0.033559
4962                 zoos -0.115260 -0.065782  0.173434

[4963 rows x 4 columns]

In [ ]:
fig = px.scatter_3d(reduced_df, x=0, y=1, z=2, hover_name='subject_term')
fig.show()

In [83]:
fig = px.scatter_matrix(df, dimensions=categories[:5], width=1600, height=800, hover_name='subject_term')
fig.show()

In [32]:
from sklearn.manifold import TSNE

tsne = TSNE(n_components=2, random_state=42)
projections = tsne.fit_transform(df.drop(columns=['subject_term', 'max_val', 'max_cat', 'frequency', 'log_frequency']))
projections = pd.DataFrame(projections)
projections.insert(0, 'subject_term', pd.Series(df['subject_term']))
projections.insert(1, 'max_category', pd.Series(df['max_cat']))
projections.insert(2, 'max_value', pd.Series(df['max_val']).map(lambda x: round(x, 2)))
projections.insert(3, 'frequency', pd.Series(df['frequency']))
projections.insert(4, 'log_frequency', pd.Series(df['log_frequency'].map(lambda x: round(x, 2))))

In [33]:
fig = px.scatter(projections, x=0, y=1, hover_name='subject_term', color='max_category', hover_data=['max_category', 'max_value', 'frequency'],
                 size='log_frequency', width=1600, height=800)
fig.show()

In [3]:
# Display top candidate subject terms for each category
threshold = 0.85
top_terms = df[df['max_val'] >= threshold]
top_terms

,subject_term,housing,bikes,homelessness,dogs,parks,construction,traffic,transit,noise,...,safety,arts,childcare,democracy,cost of living,healthcare,equity,business,max_val,max_cat
7,911,0.064987,0.008366,0.028506,0.004211,0.019045,0.052367,0.043089,0.199297,0.156667,...,0.916826,0.011021,0.006016,0.000659,0.222635,0.004493,0.128372,0.093328,0.916826,safety
8,911 calls,0.001093,0.000210,0.001697,0.000584,0.000189,0.000343,0.002229,0.008163,0.026237,...,0.912758,0.000171,0.000141,0.000417,0.001409,0.000216,0.041449,0.001121,0.912758,safety
9,AED,0.114720,0.004164,0.003576,0.008349,0.053110,0.139605,0.028903,0.089100,0.000232,...,0.952019,0.432636,0.007353,0.014249,0.699805,0.971058,0.029816,0.436054,0.971058,healthcare
10,AEI,0.103995,0.022379,0.015122,0.011507,0.036646,0.187248,0.064155,0.248632,0.003178,...,0.466485,0.942233,0.031309,0.038411,0.182843,0.299627,0.914677,0.508641,0.942233,arts
12,ALH,0.372456,0.031182,0.055090,0.015516,0.065376,0.226657,0.102050,0.327196,0.057615,...,0.491629,0.606013,0.090769,0.025806,0.432847,0.446017,0.907913,0.395068,0.907913,equity
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4925,works yards,0.003242,0.012174,0.000738,0.005707,0.001339,0.989688,0.004694,0.022379,0.010239,...,0.173268,0.611188,0.000408,0.030242,0.012682,0.001799,0.131660,0.896577,0.989688,construction
4926,worksites,0.001362,0.001846,0.000042,0.000871,0.000175,0.981891,0.006109,0.008194,0.010675,...,0.398187,0.360066,0.000167,0.012128,0.001367,0.001243,0.148610,0.974718,0.992187,infrastructure
4929,yard (facility),0.632481,0.002853,0.000052,0.002615,0.000763,0.660720,0.001144,0.007810,0.000251,...,0.113892,0.000953,0.043735,0.047451,0.002612,0.087075,0.173283,0.684531,0.990112,infrastructure
4947,zebra crosswalk markings,0.000194,0.000517,0.000115,0.000108,0.001132,0.018722,0.445787,0.475270,0.000126,...,0.963895,0.137459,0.000662,0.001794,0.006506,0.000485,0.174569,0.034514,0.977022,infrastructure
4962,zoos,0.041261,0.003561,0.033976,0.995291,0.013428,0.092841,0.029663,0.329301,0.241722,...,0.142399,0.045967,0.055178,0.005333,0.145248,0.067034,0.022508,0.096183,0.995291,dogs

In [4]:
top_terms.to_csv("top_terms.csv")

In [5]:
df.to_csv("all_terms.csv")

In [29]:
# Generate histograms of similarities per category
import plotly.graph_objects as go
import numpy as np

# fig = px.histogram(
#     df, 
#     x='housing',
#     width=500,
#     height=500,
#     nbins=20
# )
fig = go.Figure()
for cat in categories:
    fig.add_trace(go.Histogram(
        x=df[cat],
        xbins=dict(
            start=0.0,
            end=1.0,
            size=0.05
        ),
        name=cat.capitalize()
    ))
fig.update_layout(barmode='overlay', width=500)
fig.update_traces(opacity=0.75)
fig.show()

In [55]:
fig = px.histogram(
    df,
    x='max_val',
    color='max_cat',
    marginal='rug',
    hover_name='max_cat',
    width=1000,
    height=750,
    nbins=10,
    title='Most similar category of agenda items\' subject terms',
)
fig.show()

In [ ]:
for cat in categories:
    fig = px.histogram(
        df,
        x=cat,
        marginal='rug',
        nbins=20,
        width=500,
        height=500,
        # color='max_cat'
    )
    fig.show()

In [69]:
import numpy as np

counts, bins = np.histogram(df['housing'], bins=[i / 100 for i in range(0, 101, 5)])
bins = .5 * (bins[:-1] + bins[1:])
fig = px.bar(x=bins, y=counts)
fig.show()

In [67]:
bins, counts

(array([0.02502738, 0.07500468, 0.12498198, 0.17495928, 0.22493658,
        0.27491388, 0.32489118, 0.37486848, 0.42484578, 0.47482308,
        0.52480038, 0.57477768, 0.62475498, 0.67473228, 0.72470958,
        0.77468688, 0.82466418, 0.87464148, 0.92461878, 0.97459608]),
 array([3572,  257,  174,  115,   93,   90,   68,   88,   62,   56,   67,
          41,   45,   29,   17,   16,   10,   16,   27,  120]))

In [71]:
histogram_table = []
for cat in categories:
    counts, bins = np.histogram(df[cat], bins=[i / 100 for i in range(0, 101, 5)])
    histogram_table.append(counts.tolist())
    # bins = .5 * (bins[:-1] + bins[1:])
    # fig = px.bar(x=bins, y=counts)
    # fig.show()
histogram_table = pd.DataFrame(
    histogram_table,
    columns=[
        "0.00 - 0.05",
        "0.05 - 0.10",
        "0.10 - 0.15",
        "0.15 - 0.20",
        "0.20 - 0.25",
        "0.25 - 0.30",
        "0.30 - 0.35",
        "0.35 - 0.40",
        "0.40 - 0.45",
        "0.45 - 0.50",
        "0.50 - 0.55",
        "0.55 - 0.60",
        "0.60 - 0.65",
        "0.65 - 0.70",
        "0.70 - 0.75",
        "0.75 - 0.80",
        "0.80 - 0.85",
        "0.85 - 0.90",
        "0.90 - 0.95",
        "0.95 - 1.00"
    ],
    index=categories
)
histogram_table

,0.00 - 0.05,0.05 - 0.10,0.10 - 0.15,0.15 - 0.20,0.20 - 0.25,0.25 - 0.30,0.30 - 0.35,0.35 - 0.40,0.40 - 0.45,0.45 - 0.50,0.50 - 0.55,0.55 - 0.60,0.60 - 0.65,0.65 - 0.70,0.70 - 0.75,0.75 - 0.80,0.80 - 0.85,0.85 - 0.90,0.90 - 0.95,0.95 - 1.00
housing,3572,257,175,114,93,90,68,88,63,55,67,41,45,29,17,16,10,16,27,120
bikes,4352,293,104,46,27,19,12,5,3,7,4,9,4,1,3,1,0,0,3,70
homelessness,4702,142,55,25,11,5,7,2,0,1,1,1,0,0,0,1,0,2,0,8
dogs,4813,75,8,13,0,2,8,3,5,3,4,3,1,1,0,1,1,0,1,21
parks,3906,321,229,135,94,49,28,21,21,16,9,13,4,7,6,7,5,8,19,65
construction,3822,228,174,120,107,69,59,61,42,39,18,21,21,18,11,19,18,20,31,65
traffic,3910,231,132,100,59,59,32,31,24,22,21,13,22,26,26,12,29,28,52,134
transit,2995,432,235,164,142,114,120,87,76,95,58,42,40,37,26,21,34,25,42,178
noise,4621,95,41,35,20,18,16,9,6,8,6,6,8,7,9,4,14,9,8,23
energy,3572,345,229,183,106,111,70,59,35,27,19,19,10,12,16,12,15,14,23,86
climate,3785,337,221,170,114,78,62,34,23,17,12,15,11,8,10,9,14,12,14,17
infrastructure,2892,275,197,134,111,113,104,84,99,79,66,62,51,40,55,42,57,80,82,340
safety,2082,380,270,262,224,189,174,195,148,119,97,94,81,86,85,88,78,85,105,121
arts,4036,230,98,87,67,67,69,56,49,32,35,20,18,13,11,5,9,8,9,44
childcare,4281,242,177,102,38,22,11,7,5,4,1,6,3,3,4,3,3,2,7,42
democracy,4167,389,194,70,37,23,18,13,9,8,6,4,6,6,2,5,3,3,0,0
cost of living,3690,331,192,142,114,93,60,73,55,60,26,22,21,15,14,11,13,15,11,5
healthcare,3739,266,200,149,108,113,84,62,39,22,18,16,10,6,11,10,10,17,31,52
equity,2770,648,449,308,215,161,110,75,63,35,31,20,14,14,11,17,4,5,7,6
business,2595,282,177,131,108,129,129,96,110,104,88,108,109,86,80,97,110,82,119,223

In [72]:
histogram_table.to_csv('histogram_table.csv')

In [73]:
sorted(categories)

['arts',
 'bikes',
 'business',
 'childcare',
 'climate',
 'construction',
 'cost of living',
 'democracy',
 'dogs',
 'energy',
 'equity',
 'healthcare',
 'homelessness',
 'housing',
 'infrastructure',
 'noise',
 'parks',
 'safety',
 'traffic',
 'transit']

---

In [74]:
from collections import Counter

count_terms = Counter()
with open('all_items\\comma_separated_subject_terms.txt', 'r', encoding='utf-8') as file:
    for line in file:
        line = line.strip()
        count_terms[line] += 1

In [ ]:
sorted_terms = sorted(count_terms, reverse=True, key=lambda x: count_terms[x])

['rezoning',
 're-zoning',
 'zoning by-law amendment applications',
 'zoning bylaw amendments',
 'purchasing']

In [76]:
for term in sorted_terms:
    print(term, count_terms[term])

rezoning 4295
re-zoning 4295
zoning by-law amendment applications 4295
zoning bylaw amendments 4295
purchasing 3627
acquisition 3627
buying 3627
procurement 3627
sourcing 3627
tenders 3627
auditors 3356
zoning 2868
parking 2666
official plan amendments 2449
annual financial reports 2219
zoning bylaws 2187
zoning by-laws 2187
zoning bylaw project 2187
zoning project 2187
heritage buildings 2156
heritage sites 2156
heritage properties 2042
designated heritage properties 2042
listed heritage properties 2042
by-laws 2030
bylaws 2030
planning 1983
capital budgets 1966
contracts 1886
construction 1819
building 1819
property standards 1762
heritage designation 1723
operating budgets 1708
demolitions 1696
audits 1689
fences 1593
division fences 1593
line fences 1593
funding 1575
financing 1575
tenancy agreements 1515
rehabilitation (property) 1454
financial reports 1425
financial statements 1425
appeals 1420
bids 1387
public appointments 1354
agreements 1331
alcohol permits 1301
liquor licences 1301
liquor permits 1301
signs 1236
signage 1236
planning tribunals 1225
omb 1225
ontario municipal board 1225
transportation 1219
transportation services 1219
appointments 1138
business improvement areas 1120
business improvement associations 1120
budgets 1068
budgets and accounts 1068
parking regulations 1058
parking by-laws 1058
parking bylaws 1058
housing projects 1041
heritage preservation 1038
historic preservation 1038
historical preservation 1038
traffic calming 1004
redevelopment 1002
renewal 1002
revitalization 1002
BIA 994
liquor sales licences 986
greenbelts 955
parks 937
conservation areas 937
parkland 937
stop signs 937
all-way stop controls 937
technical warrants 937
front yard parking 908
trip info 891
tripinfo 891
parking prohibitions 830
no parking 830
traffic 828
motor vehicle traffic 828
motorized traffic 828
traffic conditions 828
traffic flow 828
speed humps 828
sleeping policeman 828
sleeping policemen 828
speed bumps 828
quotations 822
quotes 822
request for quotation 822
rfq 822
parking pads 820
boulevard parking 820
off street parking 820
off street permit parking 820
boards of management 815
boards of directors 815
boards of governors 815
traffic regulations 815
annual reports 794
annual report cards 794
report cards 794
ttc 783
Toronto Transit Commission 782
speed limits 773
change 758
amendments 758
conversion 758
modification 758
advisory committees 757
ad hoc committees 757
advisory groups 757
council reference groups 757
liaison committees 757
panels 757
political reference groups 757
public advisory committees 757
reference groups 757
round tables 757
roundtables 757
special committees 757
steering committees 757
sub-committees 757
subcommittees 757
task forces 757
working groups 757
affordable housing 720
affordable homes 720
special purpose bodies 701
abccs 701
abcds 701
agencies 701
boards 701
commissions 701
committees of management 701
local boards 701
boulevard cafes 697
boulevard patios (restaurants) 697
sidewalk cafes 697
sidewalk patios (restaurants) 697
applications 694
application process 694
committees of adjustment 688
committee of adjustment 688
rental housing 688
rental properties 688
rental units 688
exemptions 683
exceptions 683
permit parking 675
on-street permit parking 675
parking permits 675
housing 671
homes 671
residences 671
turn prohibitions (traffic) 662
sign permits 654
billboard permits 654
permanent sign permits 654
sign variances 654
street banner permits 654
temporary sign permits 654
festivals and special events 649
community events 649
community festivals 649
cultural events 649
events 649
festivals 649
municipal codes 646
safety 642
public safety 642
fire routes 639
fire access routes 639
traffic control systems 632
traffic signal control systems 632
traffic signal equipment 632
public health 632
site plan control 626
site plan approvals 626
tree removal 624
development 622
developing land 622
development (land) 622
land development 622
accessibility 614
barrier-free design 614
universal design 614
wheelchair accessible 614
encroachments 612
Official Plans 593
road closures 578
street closures 578
temporary highway closings 578
on-street parking 573
curb parking 573
curbside parking 573
street parking 573
proposals 565
request for proposal 565
rfp 565
investment 564
financial assistance 555
leasing 554
leases 554
property taxes 549
municipal taxes 549
property tax accounts 549
property tax bills 549
tax accounts 549
traffic signal operations 546
health coverage 538
lanes 527
traffic lanes 527
turn lanes 527
turning lanes 527
property 524
traffic signals 510
fixed time signals 510
highway traffic signals 510
pretimed signals 510
semi-actuated signals 510
traffic actuated signals 510
traffic control signals 510
traffic lights 510
financial incentives 509
licences 508
licenses 508
licensing 508
loading zones 505
drop off areas 505
drop off zones 505
loading spaces 505
pick up areas 505
pick up zones 505
theatres (facilities) 504
auditorium 504
performance spaces 504
performing arts centres 504
performing arts facilities 504
minor variances 502
variance 502
stopping prohibitions 501
parking authorities 490
parking authority 490
councillors 485
aldermen 485
alderwomen 485
city councellors 485
city councillors 485
council members 485
councilors 485
members of council 485
hearings 482
land acquisition 479
land acquisitions 479
park acquisition 479
parkland acquisition 479
parks acquisitions 479
property acquisition 479
property acquisitions 479
strategic plans 472
strategic planning 472
strategy 472
health 468
board members 460
economic development 452
business development 452
business opportunities 452
business retention 452
investment attraction 452
investment marketing 452
subsidies and grants 448
financial subsidy 448
grant and subsidy programs 448
grant programs 448
grants 448
grants programs 448
incentives 448
subsidies 448
subsidy and grant programs 448
programs 445
infrastructure 432
zoos 425
sidewalks 424
residential properties 418
residential real estate 418
awards 418
legal matters 407
legal issues 407
employees 402
staff 402
part lot control 397
street names 396
renaming 396
road names 396
street naming 396
naming 394
road reconstruction 388
road alterations 388
road narrowing 388
road widening 388
reserve funds 383
reserves and reserve funds 383
policies and procedures 377
guidelines 377
policies 377
privately-owned trees 374
private owned trees 374
private trees 374
privately owned trees 374
trees on private property 374
easements 373
labour relations 367
collective bargaining 367
employee relations 367
labor relations 367
union-management relations 367
rinks 367
subdivision (land) 366
subdivision of land 366
pedestrian crossovers 364
cross walks 364
cross-walks 364
crosswalks 364
pedestrian crosswalks 364
fees 364
administrative fees 364
admission fees 364
admission prices 364
rates 364
service charges 364
user charges 364
user fees 364
projects 363
repairs 363
pxo 362
services 362
long term care homes 360
homes for the aged 360
long term care centers 360
long term care centres 360
long term care facilities 360
nursing facilities 360
nursing homes 360
expropriations 350
compulsory purchase 350
eminent domain 350
community centres 349
board-run community centres 349
clubhouses 349
community centers 349
community complexes 349
maintenance 345
accessible permit parking 341
accessible parking permits 341
accessible parking spaces 341
designated disabled parking spaces 341
disabled parking permits 341
disabled parking spaces 341
disabled parking spots 341
disabled permit parking 341
disabled person parking permits 341
handicapped parking 341
permit parking (disabled) 341
water 338
public transit 329
local transit 329
mass transit 329
public transport 329
public transportation 329
surface transit 329
transit 329
transit services 329
urban transportation 329
improvement 325
enhancement 325
committee meetings 322
social housing 321
community housing 321
housing allowance 321
low income housing 321
non profit housing 321
non-profit housing 321
public housing 321
rent geared to income assistance 321
rent geared to income housing 321
rent subsidies 321
rent supplement 321
subsidized housing 321
subsidized rent 321
subsidized units 321
urban planning 321
city planning 321
community planning 321
regional planning 321
indoor hockey rinks 316
properties (real estate) 315
real estate 315
special occasion permits 315
taxes 313
levies 313
elections 311
polls (elections) 311
voting 311
community councils 308
arenas 305
educational institutions 303
governance structure 301
evaluation 298
review 298
reviewing 298
roads 296
circles (roads) 296
circuits (roads) 296
courts (roads) 296
crescents (roads) 296
drives (roads) 296
gardens (roads) 296
gates (roads) 296
groves (roads) 296
heights (roads) 296
roadways 296
squares (roads) 296
streets 296
terraces (roads) 296
trails (roads) 296
real estate transactions 291
public art 289
outdoor art 289
outdoor sculptures 289
outdoor statues 289
no stopping 288
compliance 285
permits 284
permit renewal 284
aboriginal peoples 283
aboriginals 283
indigenous peoples 283
native peoples 283
First Nations 283
aboriginal community 283
sidewalk maintenance 282
condominium housing 280
condominiums 280
condos 280
school boards 278
community engagement 276
assumption of services 276
persons with a disability 276
disabled 276
disabled persons 276
handicapped persons 276
people with disabilities 276
persons with disabilities 276
persons with special needs 276
physical disabilities 276
physically challenged 276
physically disabled 276
physically impaired 276
special needs 276
the physically disabled 276
watermains 274
mains 274
water mains 274
heritage conservation districts 273
heritage districts 273
historic areas 273
buildings 273
sidewalks maintenance 270
arts and culture 269
public consultation 269
community consultation 269
consultation 269
public hearing 269
equity 267
employment equity 267
fair wage 267
pay equity 267
film production 266
waterfront trail 266
police services 266
police 266
policing 266
human resources 261
fire and rescue services 259
fire fighting 259
fire services 259
fire suppression 259
firefighting 259
rescue 259
rescue operations 259
search and rescue 259
traffic management 259
traffic control 259
traffic monitoring 259
traffic operations 259
information and communication technology 256
ict 256
information and communication systems 256
information and technology 256
information technology 256
it 256
film and television industry 254
cinema industry 254
film and television cluster 254
movie industry 254
television industry 254
governance 254
municipal governance 254
energy use 249
work plans 243
service delivery 242
disease outbreaks 241
epidemics 241
pandemics 241
road safety 240
swm 239
donation 238
bequest 238
toy drive 238
road resurfacing 237
facilities 236
laneways 235
back alleys 235
mews 235
light rail transit 232
lrt 232
environmental assessments 226
ea 226
ecological assessment 226
environmental assessment 226
environmental evaluation 226
pensions 226
urban forestry 225
forestry 225
tree health 225
traffic calming measures 223
traffic calming devices 223
traffic calming methods 223
food premises 221
emergency housing 220
emergency shelters 220
homeless shelters 220
hostels (homeless) 220
planning approvals 219
development applications 219
development approval applications 219
development approvals 219
planning applications 219
planning development approvals 219
trees 218
ash trees 218
meetings 218
indians (native) 216
inuit 216
metis 216
métis 216
waterfronts 215
lakefronts 215
Exhibition Place 215
delegation of authority 212
signing authorities 212
public transit authorities 211
public transportation organizations 211
transit agencies 211
transit operating agencies 211
building records 210
land 209
costs 207
community development 206
community building 206
community capacity building 206
social development 206
security 203
policy development 201
schools 201
community use of schools 201
school cafeterias 201
school classrooms 201
school gymnasiums 201
policy making 201
legislation 201
acts 201
minutes 200
sewer and water infrastructure 200
sewer and water services 200
water and sewer infrastructure 200
water management systems 200
mixed use areas 197
child care 193
childcare 193
electricity usage 192
solid waste management 191
solid waste management planning 191
waste management 191
pedestrians 191
pedestrianization 191
city vehicles 191
city owned vehicles 191
city-owned vehicles 191
corporate fleet 191
municipal officials 190
city officials 190
development charges 188
community benefits 187
tenants 184
renters 184
bike lanes 184
bicycle lanes 184
on street bike lanes 184
urban design 183
civic improvements 183
city-owned properties 183
city owned properties 183
city properties 183
partnerships 175
parking spaces 175
parking spots 175
revenue generation 173
revenue tools 173
sustainable energy 173
wastewater treatment plants 173
sewage treatment plants 173
treatment plants 173
waste water treatment plants 173
engineering 173
corporations 172
property sales 172
land sales 172
sales of land 172
sales of property 172
employment opportunities 172
careers 172
employment 172
job applications 172
job boards 172
job openings 172
job opportunities 172
job postings 172
job vacancies 172
jobs 172
vacancies (jobs) 172
city initiatives 172
city council priorities 172
corporate campaigns 172
council priorities 172
municipal initiatives 172
cycling 171
bicycling 171
police services boards 169
police boards 169
neighbourhoods 169
cultural neighbourhoods 169
ethnic neighbourhoods 169
neighborhoods 169
schedules 168
project schedules 168
scheduling 168
timing 168
human rights 168
external services 166
consultants 166
consulting services 166
professional services 166
draft by-laws 162
draft bylaws 162
pilot projects 161
committees of council 160
council committees 160
arts and culture organizations 160
art councils 160
art organizations 160
arts councils 160
arts groups 160
cultural organizations 160
homelessness 160
loans 159
expenses 159
highways 158
parkways 158
sewage systems 158
aboriginal services 158
music 158
benefits 157
children 156
building permits 156
commercial xpress service 156
residential fastrack service 156
construction permits (right-of-way) 155
curb cut permits 155
driveway paving permits 155
driveway resurfacing permits 155
driveway widening permits 155
landscaping permits (right-if way) 155
goods 154
road construction 153
regional transportation agencies 153
commuter rail systems 153
go transit 153
intercity transportation 153
interregional public transit systems 153
interregional transit systems 153
interurban transit organizations 153
metrolinx 153
regional transit authorities 153
regional transportation authorities 153
federal governments 152
provincial governments 149
payment 149
paying 149
payment information 149
payment methods 149
payment options 149
pre-authorized payment plans 149
pre-authorized plans 149
preauthorized payments 149
bridge reconstruction 148
child care facilities 146
child care agencies 146
child care centres 146
day cares 146
day nurseries 146
home care agencies 146
home child care providers 146
nursery schools 146
restaurants 144
cafeterias 144
dining 144
eating places 144
municipal facilities 144
city facilities 144
municipal buildings 144
road maintenance 144
roads maintenance 144
summer maintenance 144
winter maintenance 144
taxi fares 142
business licences 142
business licensing 142
business permits 142
municipal licenses 142
polling 142
climate change 141
climate protection 141
boards of health 141
cultural attractions 140
sewers 140
sewerage 140
subway stations 139
vending 138
water treatment plants 138
filtration plants 138
water filtration plants 138
water treatment and supply plants 138
water treatment facilities 138
driveways 137
energy 137
energy resources 137
graffiti 137
graffiti abatement 137
graffiti crime 137
graffiti eradication 137
graffiti vandalism 137
grafitti removal 137
wages 136
earnings 136
pay 136
pay scale 136
salary 136
wage rate 136
footpaths 136
walking paths 136
collection (activity) 136
animal services 136
animal control 136
animal protection 136
animal shelters 136
animal welfare 136
humane society 136
injured animals 136
lost pets 136
missing animals 136
missing pets 136
sick animals 136
stray animals 136
stray pets 136
child 135
food 135
menus 135
heat 134
candidates 133
heating 132
ventilation and air conditioning systems 132
air conditioning 132
air conditioning systems 132
boilers 132
climate control systems 132
cooling systems 132
furnaces 132
heating systems 132
hvac 132
ventilation 132
ventilation systems 132
executive committees 132
youth 130
adolescents 130
dieting 129
taxicabs 129
cabs 129
taxis 129
standards 129
materials 129
commodities 129
rail fares 129
nutrition 127
diet 127
healthy eating 127
parking enforcement 127
civic engagement 127
citizen participation 127
civic participation 127
community involvement 127
community participation 127
public involvement 127
public participation 127
implementation 127
sidewalk repairs 126
roadside repair 126
sidewalk brick installation 126
sidewalk brick maintenance 126
sidewalk ramping 126
sidewalk replacement 126
walkway maintenance 126
walkway repair 126
bia 126
alternative energy 125
parking machines 125
pay and display machines 125
pay-and-display machines 125
multi-unit dwellings 125
multi residential apartment buildings 125
multi residential buildings 125
multi unit buildings 125
multi unit dwellings 125
multi-residential apartment buildings 125
multi-residential buildings 125
multi-unit buildings 125
multi-unit residential buildings 125
residential multi unit dwellings 125
residential multi-unit dwellings 125
municipal elections 125
recreational facilities 125
recreation facilities 125
recreational amenities 125
regulations 124
below market rent space 123
below market rent 123
below market space 123
bmrs 123
inspection 123
site inspection 123
viewing 123
community safety 122
hiring process 122
hiring 122
job recall 122
recruitment 122
selection 122
Master Plans 122
software 122
computer programs 122
commercial properties 121
office real estate 121
retail space 121
members 121
memberships 121
workplace training and development 121
continuous learning 121
corporate learning 121
employee development 121
employee training 121
job training and development 121
learning maps 121
learning plan 121
occupational training 121
on the job training 121
professional development 121
retraining at work 121
skills development in the workplace 121
staff development 121
staff training 121
training and development at work 121
work-based learning 121
economic indicators 121
zoning designations 120
permitted use requests 120
permitted uses 120
municipalities 120
boroughs 120
cities 120
counties 120
regional municipalities 120
towns 120
auctions 120
greenhouse effect 120
greenhouse gas emissions 120
road repairs 119
crack repairs 119
cut repairs 119
fixing potholes 119
pothole repairs 119
Secondary Plans 118
subways 118
underground 118
arrears 118
outstanding balances 118
outstanding bills 118
outstanding charges 118
overdue 118
past due 118
unpaid balances 118
unpaid bills 118
dogs 118
utilities 118
power utilties 118
emergency management 117
crisis management 117
disaster planning 117
disaster supply kits 117
emergency preparedness 117
emergency procedures 117
emergency supply kits 117
survival kits 117
facade improvement 117
mural program 117
sanitary sewers 117
traffic signs 116
traffic regulatory signs 116
carparks 116
car parks 116
car-parks 116
city parking lots 116
municipal parking lots 116
parking lots 116
public parking 116
railways 116
railroads 116
integrity commissioners 116
non-profit organizations 115
non profit 115
nonprofit 115
not-for-profit organizations 115
nomination 115
bridge rehabilitation 115
bridge repair 115
basement flooding 115
basement flood cleanup 115
basement flooding response 115

In [78]:
len(count_terms), df.shape

(4963, (4963, 23))

In [81]:
df.iloc[4000:4005]['subject_term'], sorted(count_terms)[4000:4005]

(4000                  smartphones
 4001                        smell
 4002                       smells
 4003    smog alert response plans
 4004                  smog alerts
 Name: subject_term, dtype: object,
 ['smartphones',
  'smell',
  'smells',
  'smog alert response plans',
  'smog alerts'])

In [82]:
df['count'] = [count_terms[term] for term in sorted(count_terms)]
df.iloc[4000:4005]

,subject_term,housing,bikes,homelessness,dogs,parks,construction,traffic,transit,noise,...,arts,childcare,democracy,cost of living,healthcare,equity,business,max_val,max_cat,count
4000,smartphones,0.000149,0.000081,0.000144,0.000110,0.000424,0.000212,0.001020,0.003768,0.000865,...,0.000138,0.000575,0.001422,0.001217,0.000681,0.008609,0.009085,0.208274,safety,9
4001,smell,0.429487,0.028681,0.028779,0.075079,0.073341,0.068760,0.057674,0.339274,0.000242,...,0.005475,0.083243,0.025044,0.003265,0.020290,0.038969,0.179108,0.429487,housing,18
4002,smells,0.506169,0.015425,0.040387,0.039075,0.040232,0.165083,0.135608,0.409253,0.003659,...,0.003116,0.109006,0.035227,0.020636,0.077477,0.092210,0.344022,0.506169,housing,18
4003,smog alert response plans,0.048042,0.001187,0.000097,0.000552,0.006480,0.009010,0.009839,0.054022,0.006045,...,0.000405,0.000324,0.004102,0.001108,0.000278,0.041730,0.118972,0.434028,safety,6
4004,smog alerts,0.075385,0.001361,0.000144,0.000416,0.004603,0.008437,0.012691,0.080629,0.014088,...,0.000277,0.000339,0.000402,0.001467,0.000160,0.002167,0.006691,0.091688,safety,2

In [84]:
count_terms['smell']

18

In [85]:
df.to_csv('all_terms.csv')