In [2]:
%pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp310-cp310-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.2.2-cp310-cp310-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp310-cp310-win_amd64.whl (11.6 MB)
Downloading numpy-2.2.2-cp310-cp310-win_amd64.whl (12.9 MB)
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   -------------------------------------- - 12.3/12.9 MB 64.1 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 53.8 MB/s eta 0:00:00
Downloading pytz-2025.1-py2.py3-none-any.whl (507 kB)
Downloading tzdata-2025.1-py2.py3-none-any.whl (346 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.2 pandas-2.2.3 pytz-2025.1 tzdata-2025.1
Note: you may need to restart the kernel to use updated packages.

In [10]:
%pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl.metadata (3.4 kB)
Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [8]:
%pip install python-calamine

Collecting python-calamine
  Downloading python_calamine-0.3.1-cp310-none-win_amd64.whl.metadata (3.3 kB)
Requirement already satisfied: packaging~=24.1 in c:\users\trraa\documents\repos\civic-dashboard\.venv\lib\site-packages (from python-calamine) (24.2)
Downloading python_calamine-0.3.1-cp310-none-win_amd64.whl (671 kB)
   ---------------------------------------- 0.0/671.7 kB ? eta -:--:--
   --------------------------------------- 671.7/671.7 kB 25.6 MB/s eta 0:00:00
Installing collected packages: python-calamine
Successfully installed python-calamine-0.3.1
Note: you may need to restart the kernel to use updated packages.

In [9]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [8]:
%pip install requests

Collecting requests
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.1-cp310-cp310-win_amd64.whl.metadata (36 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Using cached urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Downloading certifi-2025.1.31-py3-none-any.whl (166 kB)
Downloading charset_normalizer-3.4.1-cp310-cp310-win_amd64.whl (102 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.3.0-py3-none-any.whl (128 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2025.1.31 charset-normalizer-3.4.1 idna-3.10 requests-2.32.3 urllib3-2.3.0
Note: you may need to restart the kernel to use updated packages.

In [1]:
import csv
import json
import os
import pandas as pd

In [ ]:
# Download from https://open.toronto.ca/dataset/city-subject-thesaurus/
folder = "../data"
filenames = [f"{folder}/{filename}" for filename in os.listdir(folder)]
files = {}
filenames

['../data/a-bunch-of-agenda-items.csv',
 '../data/City Subject Thesaurus (CSV).csv',
 '../data/City Subject Thesaurus (xls).csv',
 '../data/City Subject Thesaurus (xls).xls',
 '../data/City Subject Thesaurus Readme.xls',
 '../data/City Subject Thesaurus.xml']

In [4]:
# LibreOffice can open it in UTF-8 but not this for some reason
files[filenames[1]] = pd.read_csv((filenames[1]), encoding='cp437')
print(filenames[1])
files[filenames[1]].sample()

../data/City Subject Thesaurus (CSV).csv

,Name,URI,Identifier,Definition(s),Source,Synonym(s),Status,Broader concept,Narrower concept,Related concept,Legacy ID
445,builders,http://vocab.toronto.ca/id/101949,101949,Builder is a person who constructs or renovate...,From 'Good Neighbour Guide for Residential Inf...,"contractors, renovators",approved,[people in property],NaN,"builders, developers",338

In [5]:
# https://stackoverflow.com/a/66062975
encoding_list = ['ascii', 'big5', 'big5hkscs', 'cp037', 'cp273', 'cp424', 'cp437', 'cp500', 'cp720', 'cp737'
                 , 'cp775', 'cp850', 'cp852', 'cp855', 'cp856', 'cp857', 'cp858', 'cp860', 'cp861', 'cp862'
                 , 'cp863', 'cp864', 'cp865', 'cp866', 'cp869', 'cp874', 'cp875', 'cp932', 'cp949', 'cp950'
                 , 'cp1006', 'cp1026', 'cp1125', 'cp1140', 'cp1250', 'cp1251', 'cp1252', 'cp1253', 'cp1254'
                 , 'cp1255', 'cp1256', 'cp1257', 'cp1258', 'euc_jp', 'euc_jis_2004', 'euc_jisx0213', 'euc_kr'
                 , 'gb2312', 'gbk', 'gb18030', 'hz', 'iso2022_jp', 'iso2022_jp_1', 'iso2022_jp_2'
                 , 'iso2022_jp_2004', 'iso2022_jp_3', 'iso2022_jp_ext', 'iso2022_kr', 'latin_1', 'iso8859_2'
                 , 'iso8859_3', 'iso8859_4', 'iso8859_5', 'iso8859_6', 'iso8859_7', 'iso8859_8', 'iso8859_9'
                 , 'iso8859_10', 'iso8859_11', 'iso8859_13', 'iso8859_14', 'iso8859_15', 'iso8859_16', 'johab'
                 , 'koi8_r', 'koi8_t', 'koi8_u', 'kz1048', 'mac_cyrillic', 'mac_greek', 'mac_iceland', 'mac_latin2'
                 , 'mac_roman', 'mac_turkish', 'ptcp154', 'shift_jis', 'shift_jis_2004', 'shift_jisx0213', 'utf_32'
                 , 'utf_32_be', 'utf_32_le', 'utf_16', 'utf_16_be', 'utf_16_le', 'utf_7', 'utf_8', 'utf_8_sig']

for encoding in encoding_list:
    worked = True
    try:
        df = pd.read_csv(filenames[0], encoding=encoding, nrows=5)
    except:
        worked = False
    if worked:
        print(encoding, ':\n', df.head())

ascii :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
big5 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
big5hkscs :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp437 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp720 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp737 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp775 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp850 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp852 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp855 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp856 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp857 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp858 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp860 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp861 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp862 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp863 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp864 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp865 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp866 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp869 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp874 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp932 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp949 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp950 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1006 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1125 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1250 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1251 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1252 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1253 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1254 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1255 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1256 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1257 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
cp1258 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
euc_jp :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
euc_jis_2004 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
euc_jisx0213 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
euc_kr :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
gb2312 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
gbk :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
gb18030 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
hz :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso2022_jp :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso2022_jp_1 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso2022_jp_2 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso2022_jp_2004 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso2022_jp_3 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso2022_jp_ext :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso2022_kr :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
latin_1 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso8859_2 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso8859_3 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso8859_4 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso8859_5 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso8859_6 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso8859_7 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso8859_8 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso8859_9 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...
3  {"id": "ID_126314", "termId": 8, "wardId": [64...
4  {"id": "ID_126323", "termId": 8, "wardId": [65...
iso8859_10 :
                                                 data
0  {"id": "ID_126322", "termId": 8, "wardId": [65...
1  {"id": "ID_126326", "termId": 8, "wardId": [68...
2  {"id": "ID_126303", "termId": 8, "wardId": [68...

In [5]:
files[filenames[1]].iloc[0]

Name                                          [actions of government]
URI                                 http://vocab.toronto.ca/id/100783
Identifier                                                     100783
Definition(s)                                             placeholder
Source                                            developed by editor
Synonym(s)                                                        NaN
Status                                                       approved
Broader concept                            [activities in government]
Narrower concept    business travel (municipal), city initiatives,...
Related concept                                                   NaN
Legacy ID                                                        3926
Name: 0, dtype: object

In [7]:
# files[filenames[2]] = pd.read_excel((filenames[2]), sheet_name='Subject Thesaurus Data', engine='calamine')
# files[filenames[2]] = pd.read_excel((filenames[2]), sheet_name='Subject Thesaurus Data', engine='xlrd')
# files[filenames[2]] = pd.read_excel((filenames[2]), sheet_name='Subject Thesaurus Data', engine='openpyxl')
files[filenames[2]] = pd.read_csv(filenames[2], encoding='utf-8')
print(filenames[2])
files[filenames[2]].sample()

../data/City Subject Thesaurus (xls).csv

,Name,URI,Identifier,Definition(s),Source,Synonym(s),Status,Broader concept,Narrower concept,Related concept,Legacy ID
1571,park benches,http://vocab.toronto.ca/id/101986,101986,placeholder,placeholder,NaN,approved,park furnishings,commemorative benches,NaN,3245

In [9]:
# From services\data-fetcher\app\data_fetcher.py
import requests
from datetime import datetime

PAGE_SIZE = 10000

def fetch_data(from_date: str, to_date: str):
    # Validate input dates
    if not validate_datetime(from_date) or not validate_datetime(to_date):
        raise ValueError("Invalid date format. Expected format: YYYY-MM-DDTHH:MM:SS.sssZ")
    
    csrf_url = 'https://secure.toronto.ca/council/api/csrf.json'
    url = "https://secure.toronto.ca/council/api/multiple/agenda-items.json"
    session = requests.Session()

    # GET request to obtain CSRF token
    response = session.get(csrf_url)
    response.raise_for_status()

    # Extract CSRF token from cookies
    cookies = session.cookies.get_dict()
    xsrf_token = cookies.get('XSRF-TOKEN')
    if not xsrf_token:
        raise Exception('XSRF token is missing')

    querystring = {"pageNumber": 0, "pageSize": PAGE_SIZE, "sortOrder": "meetingDate"}

    # Adjust payload as needed or accept parameters from the API endpoint
    payload = {
        "includeTitle": True,
        "includeSummary": True,
        "includeRecommendations": True,
        "includeDecisions": True,
        "meetingFromDate": from_date,
        "meetingToDate": to_date
    }
    headers = {
        "Content-Type": "application/json",
        "X-XSRF-TOKEN": xsrf_token
    }

    response = session.post(url, json=payload, headers=headers, params=querystring, cookies=cookies)
    response.raise_for_status()
    data = response.json()
    return data

def validate_datetime(datetime_string: str):
    try:
        datetime.strptime(datetime_string, "%Y-%m-%dT%H:%M:%S.%fZ")
        return True
    except ValueError:
        return False

In [12]:
response = fetch_data("2024-02-01T00:00:00.000Z", "2024-02-07T00:00:00.000Z")

In [13]:
response

{'TotalRecordCount': 158,
 'PageSize': 10000,
 'PageNumber': 0,
 'TotalPages': 1,
 'Records': [{'id': 'ID_132740',
   'termId': 8,
   'agendaItemId': 132740,
   'councilAgendaItemId': 132740,
   'decisionBodyId': 2583,
   'meetingId': 24787,
   'itemProcessId': 6,
   'decisionBodyName': 'Civic Appointments Committee',
   'meetingDate': 1706850000000,
   'reference': '2024.CA13.3',
   'termYear': '2024',
   'agendaCd': 'CA',
   'meetingNumber': '13',
   'itemStatus': 'RECEIVED',
   'agendaItemTitle': 'Overview of 2024 Work Plan for the Civic Appointments Committee',
   'agendaItemSummary': "<p>The Manager, Public Appointments Secretariat will deliver a presentation to the Civic Appointments Committee on the Committee's 2024 work plan.</p>",
   'agendaItemRecommendation': '<p>The City Clerk recommends that:</p>\r\n<p>&nbsp;</p>\r\n<p>1. The Civic Appointments Committee receive this report and presentation for information.</p>',
   'decisionRecommendations': '<p>The Civic Appointments Committee received&nbsp;the Item for information.</p>',
   'decisionAdvice': "<p>Robyn Summers, Manager, Public Appointments, City Clerk's Office, gave a presentation on the Public Appointments - Civic Appointments Committee 2024 Workplan.</p>",
   'subjectTerms': 'public appointments; ',
   'wardId': [45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69],
   'backgroundAttachmentId': [242568, 242569, 242817],
   'agendaItemAddress': []},
  {'id': 'ID_132739',
   'termId': 8,
   'agendaItemId': 132739,
   'councilAgendaItemId': 132739,
   'decisionBodyId': 2583,
   'meetingId': 24787,
   'itemProcessId': 6,
   'decisionBodyName': 'Civic Appointments Committee',
   'meetingDate': 1706850000000,
   'reference': '2024.CA13.2',
   'termYear': '2024',
   'agendaCd': 'CA',
   'meetingNumber': '13',
   'itemStatus': 'AMENDED',
   'agendaItemTitle': 'Selection of Candidates for Interview for the PortsToronto Board of Directors',
   'agendaItemSummary': '<p>The Civic Appointments Committee must select candidates to interview for appointment to the PortsToronto Board of Directors. Following the interviews, the Civic Appointments Committee will recommend candidates for appointment to City Council.</p>',
   'agendaItemRecommendation': '<p>The City Clerk recommends that:&nbsp;&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>1. The Civic Appointments Committee select five candidates listed in Table 1 of Confidential Attachment 1 for interview at its next meeting for appointment to the PortsToronto Board of Directors.</p>\r\n<p>&nbsp;</p>\r\n<p>2. The Civic Appointments Committee direct that Confidential Attachment 1 remain confidential in its entirety as it relates to personal matters about identifiable individuals being considered for appointment to the PortsToronto Board of Directors.</p>',
   'decisionRecommendations': '<p>The Civic Appointments Committee:&nbsp;&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>1. Selected the following candidates to interview for appointment to the Board of Directors of PortsToronto:</p>\r\n<p>&nbsp;</p>\r\n<p>PRT2-80</p>\r\n<p>PRT2-98</p>\r\n<p>PRT2-135</p>\r\n<p>PRT2-144</p>\r\n<p>&nbsp;</p>\r\n<p>2.&nbsp;Directed that Confidential Attachment 1 to the report (January 24, 2024) from the City Clerk remain confidential in its entirety as it relates to personal matters about identifiable individuals being considered for appointment to the PortsToronto Board of Directors.</p>',
   'subjectTerms': 'airports, boards of management, public appointments; boards of directors; boards of governors',
   'wardId': [45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69],
   'backgroundAttachmentId': [242565, 242566, 242567],
   'agendaItemAddress': []},
  {'id': 'ID_132736',
   'termId': 8,
   'agendaItemId': 132736,
   'councilAgendaItemId': 132736,
   'decisionBodyId': 2583,
   'meetingId': 24787,
   'itemProcessId': 6,
   'decisionBodyName': 'Civic Appointments Committee',
   'meetingDate': 1706850000000,
   'reference': '2024.CA13.1',
   'termYear': '2024',
   'agendaCd': 'CA',
   'meetingNumber': '13',
   'itemStatus': 'AMENDED',
   'agendaItemTitle': 'Appointment of Public Members to the Board of Directors of TO Live',
   'agendaItemSummary': '<p>The Civic Appointments Committee will conduct interviews and recommend four candidates to City Council for appointment to the Board of Directors of TO Live.</p>',
   'agendaItemRecommendation': '<p>The City Clerk recommends that:&nbsp;&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>1. The Civic Appointments Committee recommend four candidates to City Council for appointment to the Board of Directors of TO Live, at pleasure of Council, for a term of office ending on February 10, 2028 and until successors are appointed.</p>\r\n<p>&nbsp;</p>\r\n<p>2. City Council direct that Confidential Attachments 1 to 4 remain confidential in their entirety as they relate to personal matters about identifiable individuals being considered for appointment to the Board of Directors of TO Live.&nbsp;</p>',
   'decisionRecommendations': '<p><span style="font-size: 12pt;">The Civic Appointments Committee recommends that:</span></p>\r\n<p>&nbsp;</p>\r\n<p>1.&nbsp;City Council appoint the following three candidates to the&nbsp;Board of Directors of TO Live, at pleasure of Council, for a term of office ending on February 10, 2028 and until successors are appointed:</p>\r\n<p>&nbsp;</p>\r\n<p style="padding-left: 30px;">Brian Astl;</p>\r\n<p style="padding-left: 30px;">Robyn Citizen; and</p>\r\n<p style="padding-left: 30px;">Sun Young Yoon.</p>\r\n<p>&nbsp;</p>\r\n<p>2. City Council waive Section 2.5 Restrictions for Staff of the City of Toronto Public Appointments Policy, to appoint Wasifa Noshin&nbsp;to the Board of Directors of TO Live, at pleasure of Council, for a term of office ending on February 10, 2028 and until a successor is appointed.</p>\r\n<p>&nbsp;</p>\r\n<p>3. City Council direct that Confidential Attachments 1 to 4 to the report (January 24, 2024) from the City Clerk remain confidential in their entirety as they relate to personal matters about identifiable individuals being considered for appointment to the Board of Directors of TO Live.&nbsp;</p>',
   'decisionAdvice': "<p>Candidates' biographies</p>\r\n<p>&nbsp;</p>\r\n<p>Brian Astl</p>\r\n<p>&nbsp;</p>\r\n<p>Brian Astl is an experienced business leader and entrepreneur. He is President of Lind Equipment, the innovation leader in construction site infrastructure. Brian has a Master of Business Administration with distinction from Harvard Business School, and a Bachelor&rsquo;s degree (Honors Business Administration) with distinction from the Ivey School of Business at Western University. Brian believes in giving back to his community, and currently serves on the Board of Trustees at the Royal Ontario Museum.</p>\r\n<p>&nbsp;</p>\r\n<p>Robyn Citizen</p>\r\n<p>&nbsp;</p>\r\n<p>Robyn Citizen is a film curator, educator and Director of Programming, Festival and Cinematheque at the Toronto International Film Festival. Before joining Toronto International Film Festival's programming team, she was a Lecturer at the University of British Columbia from 2012 to 2017. Prior to that she programmed for the Human Rights Film Festival and served as Board co-chair of the local Breakthroughs Film Festival which supports emerging women and non-binary filmmakers.</p>\r\n<p>&nbsp;</p>\r\n<p>Robyn has published research on genre and ethno-racial identity in film for edited volumes and journals, been a featured speaker on festival programming and strategy, and a jury member at festivals around the world. In addition to her love of the arts, Robyn has a background in advocacy beginning her career as a community organizer while at the University of Texas then for the New York Public Interest Research Group. She earned her doctorate (PhD) with distinction&nbsp;on cultural encounters between black Americans and the Japanese in postwar era Japanese cinema from&nbsp;New York University in 2015.&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>Wasifa Noshin</p>\r\n<p>&nbsp;</p>\r\n<p>Wasifa Noshin is public service professional with a passion for helping out people and community-based and data-driven work through social and digital media strategy and innovation. Wasifa works to implement change through authentic, accurate, and engaging storytelling. She is a pursuer of compelling social media, robust project planning, and innovative research.</p>\r\n<p>&nbsp;</p>\r\n<p>A graduate of York University with a Bachelor's in Fine Arts in Theatrical Production and Design, she graduated with honours and top of her class as a Cum Laude and spent the last six years nurturing her passion and advocacy towards public art.&nbsp;She has previously held a role as the Social Media, Website, Public Relations&nbsp;and Production Administrative Assistant at York University's Theatre Department of the School of the Arts Media Performance&nbsp;and Design (AMPD). A creative communicator, with a strong work ethic, she is a quick learner who is detail-oriented with strong organization skills seeking to contribute to a team setting while gaining experience and improving her skill set. She currently works for the Ontario Public Service within the Ministry of Finance. Wasifa is proud and excited to serve on the TO Live Board.</p>\r\n<p>&nbsp;</p>\r\n<p>Sun Young Yoon</p>\r\n<p>&nbsp;</p>\r\n<p>Sun Young Yoon is a passionate arts advocate with extensive entrepreneurial experience, cultural community engagement, and a commitment to fostering vibrant, inclusive arts environments. Sun Young Yoon is a champion of local arts, bridging professional expertise and personal dedication.</p>",
   'subjectTerms': 'boards of management, public appointments; boards of directors; boards of governors',
   'wardId': [45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69],
   'backgroundAttachmentId': [242555, 242556, 242557, 242558, 242559],
   'agendaItemAddress': []},
  {'id': 'ID_132696',
   'termId': 8,
   'agendaItemId': 132696,
   'councilAgendaItemId': 132696,
   'decisionBodyId': 2643,
   'meetingId': 24794,
   'itemProcessId': 6,
   'decisionBodyName': 'Sign Variance Committee',
   'meetingDate': 1706850000000,
   'reference': '2024.SB6.8',
   'termYear': '2024',
   'agendaCd': 'SB',
   'meetingNumber': '6',
   'itemStatus': 'POSTPONE',
   'agendaItemTitle': "Appeal of the Chief Building Official's Decision for a Signage Master Plan Application for 3 wall signs on a portion of the premises at 2075 Bayview Avenue",
   'agendaItemSummary': '<p>This report addresses an appeal of the decision of the Chief Building Official and Executive Director, Toronto Building (&ldquo;CBO&rdquo;) concerning an application for a Signage Master Plan regulating a portion of the premises municipally known as 2075 Bayview Avenue (&ldquo;2075-Bayview&rdquo;) consisting of the majority of the northern elevation of a the building known as &ldquo;S-Wing&rdquo; (the "Specific Location") concerning three variances sought for three first party illuminated wall signs displaying static copy (the &ldquo;Proposed Signage Master Plan&rdquo;) . Two of the wall signs in the Proposed Signage Master Plan (&ldquo;Proposed Sign 1&rdquo; and &ldquo;Proposed Sign 2&rdquo;) would have been located on the fifth storey, and the other (&ldquo;Proposed Sign 3&rdquo;) would have been located on the sixth storey of the northerly elevation of the S-Wing building at 2075-Bayview. Sunnybrook Health Sciences Centre as represented by Permit World (the "Applicant") applied for the Proposed Signage Master Plan, as described in Attachment 1. The Applicant indicated the three signs contained in the Proposed Signage Master Plan were intended offer identification and wayfinding to guests and patients on the hospital campus.</p>\r\n<p>&nbsp;</p>\r\n<p>Notice of the application for the Proposed Signage Master Plan was provided to the public, and the CBO conducted a written hearing in accordance with the requirements of the Sign By-law. Various parties participated in the hearing and filed materials in relation thereto.</p>\r\n<p>&nbsp;</p>\r\n<p>Upon receipt of the materials provided, the CBO made the decision to deny the application for the Proposed Signage Master Plan; at this same time, the CBO also made the decision to approve a substantively different Signage Master Plan, which while addressing the same location, and similar signs, contained specific conditions regarding illumination (the &ldquo;CBO-Designed Signage Master Plan&rdquo;).&nbsp; Specially the CBO-Designed Signage Master Plan, imposed conditions on the signs, that if illuminated, the sign shall not be illuminated between the hours of 11:00 p.m. and 7:00 a.m., and that illumination shall not exceed 150 nits during the period between sunset and sunrise for the signs.</p>\r\n<p>&nbsp;</p>\r\n<p>The CBO determined that the Proposed Signage Master Plan, would not meet all nine criteria, however, the CBO, determined based on the materials presented by the Applicant and others, that a Signage Master Plan which contained conditions on the illumination of the signs in the Specific Location, would be able to meet the nine criteria as these conditions would be sufficient to mitigate the potential for adverse impacts on surrounding properties, and other criteria.&nbsp;</p>\r\n<p>&nbsp;</p>\r\n<p>After the issuance of the CBO&rsquo;s decision denying the variances requested for the Proposed Signage Master Plan, and granting the variances, subject to conditions, required for the CBO-Designed Signage Master Plan, one of the parties to the hearing, Eda Di Pierdomenico (the &ldquo;Appellant&rdquo;) filed an appeal of the CBO&rsquo;s decision.</p>\r\n<p>&nbsp;</p>\r\n<p>As a result of the Appellant filing an appeal of the CBO&rsquo;s decision, Sign Variance Committee (&ldquo;SVC&rdquo;) is now conducting an appeal de novo, meaning that the SVC are required to conduct an evaluation to determine whether the Applicant has demonstrated that the Proposed Signage Master Plan meets all nine criteria, on the basis of the information presented to the Sign Variance Committee.&nbsp; The SVC may make a decision to refuse, or grant the variances requested by the Applicant for the Proposed Signage Master Plan, or to make a decision to grant different variances, or impose conditions which the Applicant did not include in the Proposed Signage Master Plan.</p>\r\n<p>&nbsp;</p>\r\n<p>It is the CBO&rsquo;s opinion that it has not been established that the Proposed Signage Master Plan would meet all nine established criteria as contained at &sect;694-30A of the Sign By-law, but that the CBO-Designed Signage Master Plan as set out in Attachment 2 would meet all of the required criteria.</p>',
   'agendaItemRecommendation': '<p>The Chief Building Official and Executive Director, Toronto Building, recommends that:</p>\r\n<p>&nbsp;</p>\r\n<p>1. The Sign Variance Committee refuse the three requested variances to 694-21F (4)(a) required for the implementation of the Proposed Signage Master Plan consisting of three (3) wall signs located above the first storey of the northern elevation &nbsp;of the S-Wing of the Premises municipally known as 2075 Bayview Avenue, as described further in Attachment 1 of this report.</p>\r\n<p>&nbsp;</p>\r\n<p>2. The Sign Variance Committee approve the three variances to 694-21F (4)(a), each subject to subject to two conditions required for the implementation of the CBO-Designed Signage Master Plan consisting of three (3) wall signs located above the first storey of the northern elevation&nbsp; of the S-Wing of the Premises municipally known as 2075 Bayview Avenue, as described further in Attachment 2 of this report.</p>',
   'decisionRecommendations': "<p>The Sign Variance Committee:</p>\r\n<p>&nbsp;</p>\r\n<p>1. Adjourned, at the request of appellant, the matter for an Appeal of the Chief Building Official's Decision for a Signage Master Plan Application for 3 wall signs on a portion of the premises at 2075 Bayview Avenue, to its March 1, 2024 meeting.</p>",
   'subjectTerms': 'by-laws, permits, sign permits; billboard permits; permanent sign permits; sign variances; street banner permits; temporary sign permits, bylaws, permit renewal',
   'address': ['2075 Bayview Toronto Ontario  '],
   'geoLocation': ['43.7228457,-79.3728749'],
   'wardId': [59],
   'backgroundAttachmentId': [242809, 242820, 242308],
   'agendaItemAddress': [{'agendaItemId': 132696,
     'addressId': 78076,
     'streetNumber': '2075',
     'streetName': 'Bayview',
     'streetType': 'Avenue',
     'city': 'Toronto',
     'province': 'Ontario',
     'country': 'CA',
     'postalCode': 'M4N 3M5',
     'latitude': 43.7228457,
     'longitude': -79.3728749,
     'fullAddress': '2075 Bayview Avenue, Toronto, Ontario'}]},
  {'id': 'ID_132686',
   'termId': 8,
   'agendaItemId': 132686,
   'councilAgendaItemId': 132686,
   'decisionBodyId': 2643,
   'meetingId': 24794,
   'itemProcessId': 6,
   'decisionBodyName': 'Sign Variance Committee',
   'meetingDate': 1706850000000,
   'reference': '2024.SB6.4',
   'termYear': '2024',
   'agendaCd': 'SB',
   'meetingNumber': '6',
   'itemStatus': 'AMENDED',
   'agendaItemTitle': 'Overview of Sign By-law and City Policy and Procedures',
   'agendaItemSummary': '<p>The Manager, Citywide Priorities, Toronto Building will provide a presentation on Overview of the Sign By-law and City Policy and Procedures.</p>',
   'agendaItemRecommendation': '',
   'decisionRecommendations': '<p>The Sign Variance Committee:</p>\r\n<p>&nbsp;</p>\r\n<p>1. Directed that Confidential Attachment 1 and Confidential Attachment 2 remain confidential in their entirety, as they pertain to the education or training of the Members.</p>\r\n<p>&nbsp;</p>\r\n<p>2. Requested the Solicitor, Legal Services to provide a training and education session at its April 5, 2024 meeting, and a presentation on site specific By-law amendments, and the area specific restrictions under the By-law.</p>',
   'decisionAdvice': '<p>The Sign Variance Committee recessed its public session to meet in closed session&nbsp;to consider this item as it relates to the education and training of the Members.</p>',
   'subjectTerms': 'by-laws, permits, signs; bylaws, permit renewal, signage',
   'wardId': [45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69],
   'backgroundAttachmentId': [242940, 242954],
   'agendaItemAddress': []},
  {'id': 'ID_132741',
   'termId': 8,
   'agendaItemId': 132741,
   'councilAgendaItemId': 132741,
   'decisionBodyId': 2643,
   'meetingId': 24794,
   'itemProcessId': 6,
   'decisionBodyName': 'Sign Variance Committee',
   'meetingDate': 1706850000000,
   'reference': '2024.SB6.3',
   'termYear': '2024',
   'agendaCd': 'SB',
   'meetingNumber': '6',
   'itemStatus': 'RECEIVED',
   'agendaItemTitle': 'Sign Variance Committee - Roles and Expectations of Public Members',
   'agendaItemSummary': "<p>The Project Manager, Public Appointments, City Clerk's Office, will provide a presentation on the roles and expectations of Public Members of the Sign Variance Committee.</p>",
   'agendaItemRecommendation': '',
   'decisionRecommendations': "<p>The Sign Variance Committee:</p>\r\n<p>&nbsp;</p>\r\n<p>1. Received the presentation (February 2, 2024) from the&nbsp;Project Manager, Public Appointments, City Clerk's Office.</p>",